// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_hex_quantize_ap3
NumericVector cpp_hex_quantize_ap3(double icosa_triangle_x, double icosa_triangle_y, int resolution);
RcppExport SEXP _hexify_cpp_hex_quantize_ap3(SEXP icosa_triangle_xSEXP, SEXP icosa_triangle_ySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type icosa_triangle_x(icosa_triangle_xSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_y(icosa_triangle_ySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_quantize_ap3(icosa_triangle_x, icosa_triangle_y, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_center_ap3
NumericVector cpp_hex_center_ap3(double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_hex_center_ap3(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_center_ap3(i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_corners_ap3
List cpp_hex_corners_ap3(double i, double j, int resolution, double hex_radius);
RcppExport SEXP _hexify_cpp_hex_corners_ap3(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP hex_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type hex_radius(hex_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_corners_ap3(i, j, resolution, hex_radius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_cell_ap3
NumericVector cpp_lonlat_to_cell_ap3(double lon_deg, double lat_deg, int resolution);
RcppExport SEXP _hexify_cpp_lonlat_to_cell_ap3(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_cell_ap3(lon_deg, lat_deg, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_lonlat_ap3
NumericVector cpp_cell_to_lonlat_ap3(int face, double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_cell_to_lonlat_ap3(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_lonlat_ap3(face, i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_quantize_ap4
NumericVector cpp_hex_quantize_ap4(double icosa_triangle_x, double icosa_triangle_y, int resolution);
RcppExport SEXP _hexify_cpp_hex_quantize_ap4(SEXP icosa_triangle_xSEXP, SEXP icosa_triangle_ySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type icosa_triangle_x(icosa_triangle_xSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_y(icosa_triangle_ySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_quantize_ap4(icosa_triangle_x, icosa_triangle_y, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_center_ap4
NumericVector cpp_hex_center_ap4(double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_hex_center_ap4(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_center_ap4(i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_corners_ap4
List cpp_hex_corners_ap4(double i, double j, int resolution, double hex_radius);
RcppExport SEXP _hexify_cpp_hex_corners_ap4(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP hex_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type hex_radius(hex_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_corners_ap4(i, j, resolution, hex_radius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_cell_ap4
NumericVector cpp_lonlat_to_cell_ap4(double lon_deg, double lat_deg, int resolution);
RcppExport SEXP _hexify_cpp_lonlat_to_cell_ap4(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_cell_ap4(lon_deg, lat_deg, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_lonlat_ap4
NumericVector cpp_cell_to_lonlat_ap4(int face, double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_cell_to_lonlat_ap4(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_lonlat_ap4(face, i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_quantize_ap7
NumericVector cpp_hex_quantize_ap7(double icosa_triangle_x, double icosa_triangle_y, int resolution);
RcppExport SEXP _hexify_cpp_hex_quantize_ap7(SEXP icosa_triangle_xSEXP, SEXP icosa_triangle_ySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type icosa_triangle_x(icosa_triangle_xSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_y(icosa_triangle_ySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_quantize_ap7(icosa_triangle_x, icosa_triangle_y, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_center_ap7
NumericVector cpp_hex_center_ap7(double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_hex_center_ap7(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_center_ap7(i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_corners_ap7
List cpp_hex_corners_ap7(double i, double j, int resolution, double hex_radius);
RcppExport SEXP _hexify_cpp_hex_corners_ap7(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP hex_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type hex_radius(hex_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_corners_ap7(i, j, resolution, hex_radius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_cell_ap7
NumericVector cpp_lonlat_to_cell_ap7(double lon_deg, double lat_deg, int resolution);
RcppExport SEXP _hexify_cpp_lonlat_to_cell_ap7(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_cell_ap7(lon_deg, lat_deg, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_lonlat_ap7
NumericVector cpp_cell_to_lonlat_ap7(int face, double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_cell_to_lonlat_ap7(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_lonlat_ap7(face, i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_quantize_ap34
NumericVector cpp_hex_quantize_ap34(double icosa_triangle_x, double icosa_triangle_y, IntegerVector ap_seq);
RcppExport SEXP _hexify_cpp_hex_quantize_ap34(SEXP icosa_triangle_xSEXP, SEXP icosa_triangle_ySEXP, SEXP ap_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type icosa_triangle_x(icosa_triangle_xSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_y(icosa_triangle_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ap_seq(ap_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_quantize_ap34(icosa_triangle_x, icosa_triangle_y, ap_seq));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_center_ap34
NumericVector cpp_hex_center_ap34(double i, double j, IntegerVector ap_seq);
RcppExport SEXP _hexify_cpp_hex_center_ap34(SEXP iSEXP, SEXP jSEXP, SEXP ap_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ap_seq(ap_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_center_ap34(i, j, ap_seq));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_corners_ap34
List cpp_hex_corners_ap34(double i, double j, IntegerVector ap_seq, double hex_radius);
RcppExport SEXP _hexify_cpp_hex_corners_ap34(SEXP iSEXP, SEXP jSEXP, SEXP ap_seqSEXP, SEXP hex_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ap_seq(ap_seqSEXP);
    Rcpp::traits::input_parameter< double >::type hex_radius(hex_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_corners_ap34(i, j, ap_seq, hex_radius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_cell_ap34
NumericVector cpp_lonlat_to_cell_ap34(double lon_deg, double lat_deg, IntegerVector ap_seq);
RcppExport SEXP _hexify_cpp_lonlat_to_cell_ap34(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP ap_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ap_seq(ap_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_cell_ap34(lon_deg, lat_deg, ap_seq));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_lonlat_ap34
NumericVector cpp_cell_to_lonlat_ap34(int face, double i, double j, IntegerVector ap_seq);
RcppExport SEXP _hexify_cpp_cell_to_lonlat_ap34(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP ap_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ap_seq(ap_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_lonlat_ap34(face, i, j, ap_seq));
    return rcpp_result_gen;
END_RCPP
}
// cpp_test_roundtrip_ap3
bool cpp_test_roundtrip_ap3(double icosa_triangle_x, double icosa_triangle_y, int resolution);
RcppExport SEXP _hexify_cpp_test_roundtrip_ap3(SEXP icosa_triangle_xSEXP, SEXP icosa_triangle_ySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type icosa_triangle_x(icosa_triangle_xSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_y(icosa_triangle_ySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_test_roundtrip_ap3(icosa_triangle_x, icosa_triangle_y, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_test_roundtrip_ap34
bool cpp_test_roundtrip_ap34(double icosa_triangle_x, double icosa_triangle_y, IntegerVector ap_seq);
RcppExport SEXP _hexify_cpp_test_roundtrip_ap34(SEXP icosa_triangle_xSEXP, SEXP icosa_triangle_ySEXP, SEXP ap_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type icosa_triangle_x(icosa_triangle_xSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_y(icosa_triangle_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ap_seq(ap_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_test_roundtrip_ap34(icosa_triangle_x, icosa_triangle_y, ap_seq));
    return rcpp_result_gen;
END_RCPP
}
// cpp_test_roundtrip_ap4
bool cpp_test_roundtrip_ap4(double icosa_triangle_x, double icosa_triangle_y, int resolution);
RcppExport SEXP _hexify_cpp_test_roundtrip_ap4(SEXP icosa_triangle_xSEXP, SEXP icosa_triangle_ySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type icosa_triangle_x(icosa_triangle_xSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_y(icosa_triangle_ySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_test_roundtrip_ap4(icosa_triangle_x, icosa_triangle_y, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_test_roundtrip_ap7
bool cpp_test_roundtrip_ap7(double icosa_triangle_x, double icosa_triangle_y, int resolution);
RcppExport SEXP _hexify_cpp_test_roundtrip_ap7(SEXP icosa_triangle_xSEXP, SEXP icosa_triangle_ySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type icosa_triangle_x(icosa_triangle_xSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_y(icosa_triangle_ySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_test_roundtrip_ap7(icosa_triangle_x, icosa_triangle_y, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_batch_test_roundtrip_ap3
List cpp_batch_test_roundtrip_ap3(NumericVector tx_vec, NumericVector ty_vec, int resolution);
RcppExport SEXP _hexify_cpp_batch_test_roundtrip_ap3(SEXP tx_vecSEXP, SEXP ty_vecSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tx_vec(tx_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty_vec(ty_vecSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_batch_test_roundtrip_ap3(tx_vec, ty_vec, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_batch_test_roundtrip_ap4
List cpp_batch_test_roundtrip_ap4(NumericVector tx_vec, NumericVector ty_vec, int resolution);
RcppExport SEXP _hexify_cpp_batch_test_roundtrip_ap4(SEXP tx_vecSEXP, SEXP ty_vecSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tx_vec(tx_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty_vec(ty_vecSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_batch_test_roundtrip_ap4(tx_vec, ty_vec, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_batch_test_roundtrip_ap7
List cpp_batch_test_roundtrip_ap7(NumericVector tx_vec, NumericVector ty_vec, int resolution);
RcppExport SEXP _hexify_cpp_batch_test_roundtrip_ap7(SEXP tx_vecSEXP, SEXP ty_vecSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tx_vec(tx_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty_vec(ty_vecSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_batch_test_roundtrip_ap7(tx_vec, ty_vec, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_decode_z7
DataFrame cpp_decode_z7(std::string index_body, int aperture);
RcppExport SEXP _hexify_cpp_decode_z7(SEXP index_bodySEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index_body(index_bodySEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_decode_z7(index_body, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_icosa_tri_to_quad_ij
Rcpp::List cpp_icosa_tri_to_quad_ij(int icosa_triangle_face, double icosa_triangle_x, double icosa_triangle_y, int aperture, int resolution);
RcppExport SEXP _hexify_cpp_icosa_tri_to_quad_ij(SEXP icosa_triangle_faceSEXP, SEXP icosa_triangle_xSEXP, SEXP icosa_triangle_ySEXP, SEXP apertureSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type icosa_triangle_face(icosa_triangle_faceSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_x(icosa_triangle_xSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_y(icosa_triangle_ySEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_icosa_tri_to_quad_ij(icosa_triangle_face, icosa_triangle_x, icosa_triangle_y, aperture, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_icosa_tri_to_quad_xy
Rcpp::List cpp_icosa_tri_to_quad_xy(int icosa_triangle_face, double icosa_triangle_x, double icosa_triangle_y);
RcppExport SEXP _hexify_cpp_icosa_tri_to_quad_xy(SEXP icosa_triangle_faceSEXP, SEXP icosa_triangle_xSEXP, SEXP icosa_triangle_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type icosa_triangle_face(icosa_triangle_faceSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_x(icosa_triangle_xSEXP);
    Rcpp::traits::input_parameter< double >::type icosa_triangle_y(icosa_triangle_ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_icosa_tri_to_quad_xy(icosa_triangle_face, icosa_triangle_x, icosa_triangle_y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_quad_xy_to_icosa_tri
Rcpp::List cpp_quad_xy_to_icosa_tri(int quad, double quad_x, double quad_y);
RcppExport SEXP _hexify_cpp_quad_xy_to_icosa_tri(SEXP quadSEXP, SEXP quad_xSEXP, SEXP quad_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type quad(quadSEXP);
    Rcpp::traits::input_parameter< double >::type quad_x(quad_xSEXP);
    Rcpp::traits::input_parameter< double >::type quad_y(quad_ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_quad_xy_to_icosa_tri(quad, quad_x, quad_y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_quad_ij_to_xy
Rcpp::List cpp_quad_ij_to_xy(int quad, double i, double j, int aperture, int resolution);
RcppExport SEXP _hexify_cpp_quad_ij_to_xy(SEXP quadSEXP, SEXP iSEXP, SEXP jSEXP, SEXP apertureSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type quad(quadSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_quad_ij_to_xy(quad, i, j, aperture, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_quad_ij
Rcpp::List cpp_lonlat_to_quad_ij(double lon_deg, double lat_deg, int aperture, int resolution);
RcppExport SEXP _hexify_cpp_lonlat_to_quad_ij(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP apertureSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_quad_ij(lon_deg, lat_deg, aperture, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_quad_ij_to_cell
NumericVector cpp_quad_ij_to_cell(IntegerVector quad, NumericVector i, NumericVector j, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_quad_ij_to_cell(SEXP quadSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type quad(quadSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_quad_ij_to_cell(quad, i, j, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_cell
NumericVector cpp_lonlat_to_cell(NumericVector lon, NumericVector lat, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_lonlat_to_cell(SEXP lonSEXP, SEXP latSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_cell(lon, lat, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_lonlat
DataFrame cpp_cell_to_lonlat(NumericVector cell_id, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_cell_to_lonlat(SEXP cell_idSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cell_id(cell_idSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_lonlat(cell_id, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_quad_ij
DataFrame cpp_cell_to_quad_ij(NumericVector cell_id, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_cell_to_quad_ij(SEXP cell_idSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cell_id(cell_idSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_quad_ij(cell_id, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_quad_xy
DataFrame cpp_cell_to_quad_xy(NumericVector cell_id, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_cell_to_quad_xy(SEXP cell_idSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cell_id(cell_idSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_quad_xy(cell_id, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_quad_xy_to_cell
NumericVector cpp_quad_xy_to_cell(IntegerVector quad, NumericVector quad_x, NumericVector quad_y, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_quad_xy_to_cell(SEXP quadSEXP, SEXP quad_xSEXP, SEXP quad_ySEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type quad(quadSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type quad_x(quad_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type quad_y(quad_ySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_quad_xy_to_cell(quad, quad_x, quad_y, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_icosa_tri
DataFrame cpp_cell_to_icosa_tri(NumericVector cell_id, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_cell_to_icosa_tri(SEXP cell_idSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cell_id(cell_idSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_icosa_tri(cell_id, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_quad_ij_to_icosa_tri
DataFrame cpp_quad_ij_to_icosa_tri(IntegerVector quad, NumericVector i, NumericVector j, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_quad_ij_to_icosa_tri(SEXP quadSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type quad(quadSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_quad_ij_to_icosa_tri(quad, i, j, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_polygon
DataFrame cpp_cell_to_polygon(NumericVector cell_id, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_cell_to_polygon(SEXP cell_idSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cell_id(cell_idSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_polygon(cell_id, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_corners
List cpp_cell_to_corners(NumericVector cell_id, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_cell_to_corners(SEXP cell_idSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cell_id(cell_idSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_corners(cell_id, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_cell_ap43
NumericVector cpp_lonlat_to_cell_ap43(NumericVector lon, NumericVector lat, int resolution, int mixed_aperture_level);
RcppExport SEXP _hexify_cpp_lonlat_to_cell_ap43(SEXP lonSEXP, SEXP latSEXP, SEXP resolutionSEXP, SEXP mixed_aperture_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type mixed_aperture_level(mixed_aperture_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_cell_ap43(lon, lat, resolution, mixed_aperture_level));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_lonlat_ap43
DataFrame cpp_cell_to_lonlat_ap43(NumericVector cell_id, int resolution, int mixed_aperture_level);
RcppExport SEXP _hexify_cpp_cell_to_lonlat_ap43(SEXP cell_idSEXP, SEXP resolutionSEXP, SEXP mixed_aperture_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cell_id(cell_idSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type mixed_aperture_level(mixed_aperture_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_lonlat_ap43(cell_id, resolution, mixed_aperture_level));
    return rcpp_result_gen;
END_RCPP
}
// cpp_icosa_tri_to_plane
DataFrame cpp_icosa_tri_to_plane(IntegerVector icosa_triangle_face, NumericVector icosa_triangle_x, NumericVector icosa_triangle_y);
RcppExport SEXP _hexify_cpp_icosa_tri_to_plane(SEXP icosa_triangle_faceSEXP, SEXP icosa_triangle_xSEXP, SEXP icosa_triangle_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type icosa_triangle_face(icosa_triangle_faceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type icosa_triangle_x(icosa_triangle_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type icosa_triangle_y(icosa_triangle_ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_icosa_tri_to_plane(icosa_triangle_face, icosa_triangle_x, icosa_triangle_y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_plane
DataFrame cpp_cell_to_plane(NumericVector cell_id, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_cell_to_plane(SEXP cell_idSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cell_id(cell_idSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_plane(cell_id, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_plane
DataFrame cpp_lonlat_to_plane(NumericVector lon, NumericVector lat);
RcppExport SEXP _hexify_cpp_lonlat_to_plane(SEXP lonSEXP, SEXP latSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_plane(lon, lat));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_index
std::string cpp_cell_to_index(int face, double i, double j, int resolution, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_cell_to_index(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_index(face, i, j, resolution, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_index_to_cell
Rcpp::List cpp_index_to_cell(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_index_to_cell(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_index_to_cell(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_parent_index
std::string cpp_get_parent_index(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_get_parent_index(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_parent_index(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_children_indices
Rcpp::StringVector cpp_get_children_indices(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_get_children_indices(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_children_indices(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_index_resolution
int cpp_get_index_resolution(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_get_index_resolution(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_index_resolution(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compare_indices
int cpp_compare_indices(std::string idx1, std::string idx2);
RcppExport SEXP _hexify_cpp_compare_indices(SEXP idx1SEXP, SEXP idx2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type idx1(idx1SEXP);
    Rcpp::traits::input_parameter< std::string >::type idx2(idx2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compare_indices(idx1, idx2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_is_valid_index_type
bool cpp_is_valid_index_type(int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_is_valid_index_type(SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_is_valid_index_type(aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_default_index_type
std::string cpp_get_default_index_type(int aperture);
RcppExport SEXP _hexify_cpp_get_default_index_type(SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_default_index_type(aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_index_ap3
std::string cpp_lonlat_to_index_ap3(double lon_deg, double lat_deg, int resolution, std::string index_type);
RcppExport SEXP _hexify_cpp_lonlat_to_index_ap3(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_index_ap3(lon_deg, lat_deg, resolution, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_index_ap4
std::string cpp_lonlat_to_index_ap4(double lon_deg, double lat_deg, int resolution, std::string index_type);
RcppExport SEXP _hexify_cpp_lonlat_to_index_ap4(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_index_ap4(lon_deg, lat_deg, resolution, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_index_ap7
std::string cpp_lonlat_to_index_ap7(double lon_deg, double lat_deg, int resolution, std::string index_type);
RcppExport SEXP _hexify_cpp_lonlat_to_index_ap7(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_index_ap7(lon_deg, lat_deg, resolution, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_index
std::string cpp_lonlat_to_index(double lon_deg, double lat_deg, int resolution, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_lonlat_to_index(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_index(lon_deg, lat_deg, resolution, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_index_to_lonlat
Rcpp::NumericVector cpp_index_to_lonlat(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_index_to_lonlat(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_index_to_lonlat(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cell_to_index
std::string cell_to_index(int face, Rcpp::NumericVector i, Rcpp::NumericVector j, int resolution, int aperture, std::string index_type);
RcppExport SEXP _hexify_cell_to_index(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cell_to_index(face, i, j, resolution, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// index_to_cell
Rcpp::List index_to_cell(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_index_to_cell(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(index_to_cell(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// get_parent_index
std::string get_parent_index(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_get_parent_index(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_parent_index(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// get_children_indices
std::vector<std::string> get_children_indices(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_get_children_indices(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_children_indices(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// get_index_resolution
int get_index_resolution(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_get_index_resolution(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_index_resolution(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_z7_canonical_form
std::string cpp_z7_canonical_form(std::string index, int max_iterations);
RcppExport SEXP _hexify_cpp_z7_canonical_form(SEXP indexSEXP, SEXP max_iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_z7_canonical_form(index, max_iterations));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_index_z3_quantize_digits
List cpp_hex_index_z3_quantize_digits(double tx, double ty, int eff_res, double center_thr, LogicalVector flip_classes);
RcppExport SEXP _hexify_cpp_hex_index_z3_quantize_digits(SEXP txSEXP, SEXP tySEXP, SEXP eff_resSEXP, SEXP center_thrSEXP, SEXP flip_classesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< int >::type eff_res(eff_resSEXP);
    Rcpp::traits::input_parameter< double >::type center_thr(center_thrSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type flip_classes(flip_classesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_index_z3_quantize_digits(tx, ty, eff_res, center_thr, flip_classes));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_index_z3_center
List cpp_hex_index_z3_center(IntegerVector d, LogicalVector flip_classes);
RcppExport SEXP _hexify_cpp_hex_index_z3_center(SEXP dSEXP, SEXP flip_classesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type flip_classes(flip_classesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_index_z3_center(d, flip_classes));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_index_z3_corners
List cpp_hex_index_z3_corners(IntegerVector digs, LogicalVector flip_classes, double hex_radius);
RcppExport SEXP _hexify_cpp_hex_index_z3_corners(SEXP digsSEXP, SEXP flip_classesSEXP, SEXP hex_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type digs(digsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type flip_classes(flip_classesSEXP);
    Rcpp::traits::input_parameter< double >::type hex_radius(hex_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_index_z3_corners(digs, flip_classes, hex_radius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_build_icosa
void cpp_build_icosa(double vert0_lon_deg, double vert0_lat_deg, double azimuth_deg);
RcppExport SEXP _hexify_cpp_build_icosa(SEXP vert0_lon_degSEXP, SEXP vert0_lat_degSEXP, SEXP azimuth_degSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type vert0_lon_deg(vert0_lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type vert0_lat_deg(vert0_lat_degSEXP);
    Rcpp::traits::input_parameter< double >::type azimuth_deg(azimuth_degSEXP);
    cpp_build_icosa(vert0_lon_deg, vert0_lat_deg, azimuth_deg);
    return R_NilValue;
END_RCPP
}
// cpp_which_face
int cpp_which_face(double lon_deg, double lat_deg);
RcppExport SEXP _hexify_cpp_which_face(SEXP lon_degSEXP, SEXP lat_degSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_which_face(lon_deg, lat_deg));
    return rcpp_result_gen;
END_RCPP
}
// cpp_face_centers
DataFrame cpp_face_centers();
RcppExport SEXP _hexify_cpp_face_centers() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_face_centers());
    return rcpp_result_gen;
END_RCPP
}
// cpp_snyder_forward
NumericVector cpp_snyder_forward(double lon_deg, double lat_deg);
RcppExport SEXP _hexify_cpp_snyder_forward(SEXP lon_degSEXP, SEXP lat_degSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_snyder_forward(lon_deg, lat_deg));
    return rcpp_result_gen;
END_RCPP
}
// cpp_project_to_icosa_triangle
NumericVector cpp_project_to_icosa_triangle(int face, double lon_deg, double lat_deg);
RcppExport SEXP _hexify_cpp_project_to_icosa_triangle(SEXP faceSEXP, SEXP lon_degSEXP, SEXP lat_degSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_project_to_icosa_triangle(face, lon_deg, lat_deg));
    return rcpp_result_gen;
END_RCPP
}
// cpp_snyder_inv_set_precision
void cpp_snyder_inv_set_precision(std::string mode, Rcpp::Nullable<double> tol, Rcpp::Nullable<int> max_iters);
RcppExport SEXP _hexify_cpp_snyder_inv_set_precision(SEXP modeSEXP, SEXP tolSEXP, SEXP max_itersSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type max_iters(max_itersSEXP);
    cpp_snyder_inv_set_precision(mode, tol, max_iters);
    return R_NilValue;
END_RCPP
}
// cpp_snyder_inv_get_precision
Rcpp::NumericVector cpp_snyder_inv_get_precision();
RcppExport SEXP _hexify_cpp_snyder_inv_get_precision() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_snyder_inv_get_precision());
    return rcpp_result_gen;
END_RCPP
}
// cpp_snyder_inv_set_verbose
void cpp_snyder_inv_set_verbose(bool v);
RcppExport SEXP _hexify_cpp_snyder_inv_set_verbose(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type v(vSEXP);
    cpp_snyder_inv_set_verbose(v);
    return R_NilValue;
END_RCPP
}
// cpp_snyder_inv_get_stats_and_reset
Rcpp::IntegerVector cpp_snyder_inv_get_stats_and_reset();
RcppExport SEXP _hexify_cpp_snyder_inv_get_stats_and_reset() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_snyder_inv_get_stats_and_reset());
    return rcpp_result_gen;
END_RCPP
}
// cpp_face_xy_to_ll
Rcpp::NumericVector cpp_face_xy_to_ll(double x, double y, int face, Rcpp::Nullable<double> tol, Rcpp::Nullable<int> max_iters);
RcppExport SEXP _hexify_cpp_face_xy_to_ll(SEXP xSEXP, SEXP ySEXP, SEXP faceSEXP, SEXP tolSEXP, SEXP max_itersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type max_iters(max_itersSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_face_xy_to_ll(x, y, face, tol, max_iters));
    return rcpp_result_gen;
END_RCPP
}
// cpp_icosa_face_params
Rcpp::NumericVector cpp_icosa_face_params(int face);
RcppExport SEXP _hexify_cpp_icosa_face_params(SEXP faceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_icosa_face_params(face));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_index_face_to_lonlat
Rcpp::NumericVector cpp_hex_index_face_to_lonlat(double x, double y, double cen_lat, double cen_lon, double face_azimuth_offset, bool degrees, Rcpp::Nullable<double> tol, Rcpp::Nullable<int> max_iters);
RcppExport SEXP _hexify_cpp_hex_index_face_to_lonlat(SEXP xSEXP, SEXP ySEXP, SEXP cen_latSEXP, SEXP cen_lonSEXP, SEXP face_azimuth_offsetSEXP, SEXP degreesSEXP, SEXP tolSEXP, SEXP max_itersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type cen_lat(cen_latSEXP);
    Rcpp::traits::input_parameter< double >::type cen_lon(cen_lonSEXP);
    Rcpp::traits::input_parameter< double >::type face_azimuth_offset(face_azimuth_offsetSEXP);
    Rcpp::traits::input_parameter< bool >::type degrees(degreesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type max_iters(max_itersSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_index_face_to_lonlat(x, y, cen_lat, cen_lon, face_azimuth_offset, degrees, tol, max_iters));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hexify_cpp_hex_quantize_ap3", (DL_FUNC) &_hexify_cpp_hex_quantize_ap3, 3},
    {"_hexify_cpp_hex_center_ap3", (DL_FUNC) &_hexify_cpp_hex_center_ap3, 3},
    {"_hexify_cpp_hex_corners_ap3", (DL_FUNC) &_hexify_cpp_hex_corners_ap3, 4},
    {"_hexify_cpp_lonlat_to_cell_ap3", (DL_FUNC) &_hexify_cpp_lonlat_to_cell_ap3, 3},
    {"_hexify_cpp_cell_to_lonlat_ap3", (DL_FUNC) &_hexify_cpp_cell_to_lonlat_ap3, 4},
    {"_hexify_cpp_hex_quantize_ap4", (DL_FUNC) &_hexify_cpp_hex_quantize_ap4, 3},
    {"_hexify_cpp_hex_center_ap4", (DL_FUNC) &_hexify_cpp_hex_center_ap4, 3},
    {"_hexify_cpp_hex_corners_ap4", (DL_FUNC) &_hexify_cpp_hex_corners_ap4, 4},
    {"_hexify_cpp_lonlat_to_cell_ap4", (DL_FUNC) &_hexify_cpp_lonlat_to_cell_ap4, 3},
    {"_hexify_cpp_cell_to_lonlat_ap4", (DL_FUNC) &_hexify_cpp_cell_to_lonlat_ap4, 4},
    {"_hexify_cpp_hex_quantize_ap7", (DL_FUNC) &_hexify_cpp_hex_quantize_ap7, 3},
    {"_hexify_cpp_hex_center_ap7", (DL_FUNC) &_hexify_cpp_hex_center_ap7, 3},
    {"_hexify_cpp_hex_corners_ap7", (DL_FUNC) &_hexify_cpp_hex_corners_ap7, 4},
    {"_hexify_cpp_lonlat_to_cell_ap7", (DL_FUNC) &_hexify_cpp_lonlat_to_cell_ap7, 3},
    {"_hexify_cpp_cell_to_lonlat_ap7", (DL_FUNC) &_hexify_cpp_cell_to_lonlat_ap7, 4},
    {"_hexify_cpp_hex_quantize_ap34", (DL_FUNC) &_hexify_cpp_hex_quantize_ap34, 3},
    {"_hexify_cpp_hex_center_ap34", (DL_FUNC) &_hexify_cpp_hex_center_ap34, 3},
    {"_hexify_cpp_hex_corners_ap34", (DL_FUNC) &_hexify_cpp_hex_corners_ap34, 4},
    {"_hexify_cpp_lonlat_to_cell_ap34", (DL_FUNC) &_hexify_cpp_lonlat_to_cell_ap34, 3},
    {"_hexify_cpp_cell_to_lonlat_ap34", (DL_FUNC) &_hexify_cpp_cell_to_lonlat_ap34, 4},
    {"_hexify_cpp_test_roundtrip_ap3", (DL_FUNC) &_hexify_cpp_test_roundtrip_ap3, 3},
    {"_hexify_cpp_test_roundtrip_ap34", (DL_FUNC) &_hexify_cpp_test_roundtrip_ap34, 3},
    {"_hexify_cpp_test_roundtrip_ap4", (DL_FUNC) &_hexify_cpp_test_roundtrip_ap4, 3},
    {"_hexify_cpp_test_roundtrip_ap7", (DL_FUNC) &_hexify_cpp_test_roundtrip_ap7, 3},
    {"_hexify_cpp_batch_test_roundtrip_ap3", (DL_FUNC) &_hexify_cpp_batch_test_roundtrip_ap3, 3},
    {"_hexify_cpp_batch_test_roundtrip_ap4", (DL_FUNC) &_hexify_cpp_batch_test_roundtrip_ap4, 3},
    {"_hexify_cpp_batch_test_roundtrip_ap7", (DL_FUNC) &_hexify_cpp_batch_test_roundtrip_ap7, 3},
    {"_hexify_cpp_decode_z7", (DL_FUNC) &_hexify_cpp_decode_z7, 2},
    {"_hexify_cpp_icosa_tri_to_quad_ij", (DL_FUNC) &_hexify_cpp_icosa_tri_to_quad_ij, 5},
    {"_hexify_cpp_icosa_tri_to_quad_xy", (DL_FUNC) &_hexify_cpp_icosa_tri_to_quad_xy, 3},
    {"_hexify_cpp_quad_xy_to_icosa_tri", (DL_FUNC) &_hexify_cpp_quad_xy_to_icosa_tri, 3},
    {"_hexify_cpp_quad_ij_to_xy", (DL_FUNC) &_hexify_cpp_quad_ij_to_xy, 5},
    {"_hexify_cpp_lonlat_to_quad_ij", (DL_FUNC) &_hexify_cpp_lonlat_to_quad_ij, 4},
    {"_hexify_cpp_quad_ij_to_cell", (DL_FUNC) &_hexify_cpp_quad_ij_to_cell, 5},
    {"_hexify_cpp_lonlat_to_cell", (DL_FUNC) &_hexify_cpp_lonlat_to_cell, 4},
    {"_hexify_cpp_cell_to_lonlat", (DL_FUNC) &_hexify_cpp_cell_to_lonlat, 3},
    {"_hexify_cpp_cell_to_quad_ij", (DL_FUNC) &_hexify_cpp_cell_to_quad_ij, 3},
    {"_hexify_cpp_cell_to_quad_xy", (DL_FUNC) &_hexify_cpp_cell_to_quad_xy, 3},
    {"_hexify_cpp_quad_xy_to_cell", (DL_FUNC) &_hexify_cpp_quad_xy_to_cell, 5},
    {"_hexify_cpp_cell_to_icosa_tri", (DL_FUNC) &_hexify_cpp_cell_to_icosa_tri, 3},
    {"_hexify_cpp_quad_ij_to_icosa_tri", (DL_FUNC) &_hexify_cpp_quad_ij_to_icosa_tri, 5},
    {"_hexify_cpp_cell_to_polygon", (DL_FUNC) &_hexify_cpp_cell_to_polygon, 3},
    {"_hexify_cpp_cell_to_corners", (DL_FUNC) &_hexify_cpp_cell_to_corners, 3},
    {"_hexify_cpp_lonlat_to_cell_ap43", (DL_FUNC) &_hexify_cpp_lonlat_to_cell_ap43, 4},
    {"_hexify_cpp_cell_to_lonlat_ap43", (DL_FUNC) &_hexify_cpp_cell_to_lonlat_ap43, 3},
    {"_hexify_cpp_icosa_tri_to_plane", (DL_FUNC) &_hexify_cpp_icosa_tri_to_plane, 3},
    {"_hexify_cpp_cell_to_plane", (DL_FUNC) &_hexify_cpp_cell_to_plane, 3},
    {"_hexify_cpp_lonlat_to_plane", (DL_FUNC) &_hexify_cpp_lonlat_to_plane, 2},
    {"_hexify_cpp_cell_to_index", (DL_FUNC) &_hexify_cpp_cell_to_index, 6},
    {"_hexify_cpp_index_to_cell", (DL_FUNC) &_hexify_cpp_index_to_cell, 3},
    {"_hexify_cpp_get_parent_index", (DL_FUNC) &_hexify_cpp_get_parent_index, 3},
    {"_hexify_cpp_get_children_indices", (DL_FUNC) &_hexify_cpp_get_children_indices, 3},
    {"_hexify_cpp_get_index_resolution", (DL_FUNC) &_hexify_cpp_get_index_resolution, 3},
    {"_hexify_cpp_compare_indices", (DL_FUNC) &_hexify_cpp_compare_indices, 2},
    {"_hexify_cpp_is_valid_index_type", (DL_FUNC) &_hexify_cpp_is_valid_index_type, 2},
    {"_hexify_cpp_get_default_index_type", (DL_FUNC) &_hexify_cpp_get_default_index_type, 1},
    {"_hexify_cpp_lonlat_to_index_ap3", (DL_FUNC) &_hexify_cpp_lonlat_to_index_ap3, 4},
    {"_hexify_cpp_lonlat_to_index_ap4", (DL_FUNC) &_hexify_cpp_lonlat_to_index_ap4, 4},
    {"_hexify_cpp_lonlat_to_index_ap7", (DL_FUNC) &_hexify_cpp_lonlat_to_index_ap7, 4},
    {"_hexify_cpp_lonlat_to_index", (DL_FUNC) &_hexify_cpp_lonlat_to_index, 5},
    {"_hexify_cpp_index_to_lonlat", (DL_FUNC) &_hexify_cpp_index_to_lonlat, 3},
    {"_hexify_cell_to_index", (DL_FUNC) &_hexify_cell_to_index, 6},
    {"_hexify_index_to_cell", (DL_FUNC) &_hexify_index_to_cell, 3},
    {"_hexify_get_parent_index", (DL_FUNC) &_hexify_get_parent_index, 3},
    {"_hexify_get_children_indices", (DL_FUNC) &_hexify_get_children_indices, 3},
    {"_hexify_get_index_resolution", (DL_FUNC) &_hexify_get_index_resolution, 3},
    {"_hexify_cpp_z7_canonical_form", (DL_FUNC) &_hexify_cpp_z7_canonical_form, 2},
    {"_hexify_cpp_hex_index_z3_quantize_digits", (DL_FUNC) &_hexify_cpp_hex_index_z3_quantize_digits, 5},
    {"_hexify_cpp_hex_index_z3_center", (DL_FUNC) &_hexify_cpp_hex_index_z3_center, 2},
    {"_hexify_cpp_hex_index_z3_corners", (DL_FUNC) &_hexify_cpp_hex_index_z3_corners, 3},
    {"_hexify_cpp_build_icosa", (DL_FUNC) &_hexify_cpp_build_icosa, 3},
    {"_hexify_cpp_which_face", (DL_FUNC) &_hexify_cpp_which_face, 2},
    {"_hexify_cpp_face_centers", (DL_FUNC) &_hexify_cpp_face_centers, 0},
    {"_hexify_cpp_snyder_forward", (DL_FUNC) &_hexify_cpp_snyder_forward, 2},
    {"_hexify_cpp_project_to_icosa_triangle", (DL_FUNC) &_hexify_cpp_project_to_icosa_triangle, 3},
    {"_hexify_cpp_snyder_inv_set_precision", (DL_FUNC) &_hexify_cpp_snyder_inv_set_precision, 3},
    {"_hexify_cpp_snyder_inv_get_precision", (DL_FUNC) &_hexify_cpp_snyder_inv_get_precision, 0},
    {"_hexify_cpp_snyder_inv_set_verbose", (DL_FUNC) &_hexify_cpp_snyder_inv_set_verbose, 1},
    {"_hexify_cpp_snyder_inv_get_stats_and_reset", (DL_FUNC) &_hexify_cpp_snyder_inv_get_stats_and_reset, 0},
    {"_hexify_cpp_face_xy_to_ll", (DL_FUNC) &_hexify_cpp_face_xy_to_ll, 5},
    {"_hexify_cpp_icosa_face_params", (DL_FUNC) &_hexify_cpp_icosa_face_params, 1},
    {"_hexify_cpp_hex_index_face_to_lonlat", (DL_FUNC) &_hexify_cpp_hex_index_face_to_lonlat, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_hexify(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
