// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_hex_quantify_ap3
Rcpp::NumericVector cpp_hex_quantify_ap3(double tx, double ty, int resolution);
RcppExport SEXP _hexify_cpp_hex_quantify_ap3(SEXP txSEXP, SEXP tySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_quantify_ap3(tx, ty, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_center_ap3
Rcpp::NumericVector cpp_hex_center_ap3(double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_hex_center_ap3(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_center_ap3(i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_corners_ap3
Rcpp::List cpp_hex_corners_ap3(double i, double j, int resolution, double hex_radius);
RcppExport SEXP _hexify_cpp_hex_corners_ap3(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP hex_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type hex_radius(hex_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_corners_ap3(i, j, resolution, hex_radius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_cell_ap3
Rcpp::NumericVector cpp_lonlat_to_cell_ap3(double lon_deg, double lat_deg, int resolution);
RcppExport SEXP _hexify_cpp_lonlat_to_cell_ap3(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_cell_ap3(lon_deg, lat_deg, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_lonlat_ap3
Rcpp::NumericVector cpp_cell_to_lonlat_ap3(int face, double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_cell_to_lonlat_ap3(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_lonlat_ap3(face, i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_quantify_ap4
NumericVector cpp_hex_quantify_ap4(double tx, double ty, int resolution);
RcppExport SEXP _hexify_cpp_hex_quantify_ap4(SEXP txSEXP, SEXP tySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_quantify_ap4(tx, ty, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_center_ap4
NumericVector cpp_hex_center_ap4(double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_hex_center_ap4(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_center_ap4(i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_corners_ap4
List cpp_hex_corners_ap4(double i, double j, int resolution, double hex_radius);
RcppExport SEXP _hexify_cpp_hex_corners_ap4(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP hex_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type hex_radius(hex_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_corners_ap4(i, j, resolution, hex_radius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_cell_ap4
NumericVector cpp_lonlat_to_cell_ap4(double lon_deg, double lat_deg, int resolution);
RcppExport SEXP _hexify_cpp_lonlat_to_cell_ap4(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_cell_ap4(lon_deg, lat_deg, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_lonlat_ap4
NumericVector cpp_cell_to_lonlat_ap4(int face, double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_cell_to_lonlat_ap4(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_lonlat_ap4(face, i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_quantify_ap7
NumericVector cpp_hex_quantify_ap7(double tx, double ty, int resolution);
RcppExport SEXP _hexify_cpp_hex_quantify_ap7(SEXP txSEXP, SEXP tySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_quantify_ap7(tx, ty, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_center_ap7
NumericVector cpp_hex_center_ap7(double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_hex_center_ap7(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_center_ap7(i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_corners_ap7
List cpp_hex_corners_ap7(double i, double j, int resolution, double hex_radius);
RcppExport SEXP _hexify_cpp_hex_corners_ap7(SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP hex_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type hex_radius(hex_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_corners_ap7(i, j, resolution, hex_radius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_cell_ap7
NumericVector cpp_lonlat_to_cell_ap7(double lon_deg, double lat_deg, int resolution);
RcppExport SEXP _hexify_cpp_lonlat_to_cell_ap7(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_cell_ap7(lon_deg, lat_deg, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_lonlat_ap7
NumericVector cpp_cell_to_lonlat_ap7(int face, double i, double j, int resolution);
RcppExport SEXP _hexify_cpp_cell_to_lonlat_ap7(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_lonlat_ap7(face, i, j, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_quantify_ap34
Rcpp::NumericVector cpp_hex_quantify_ap34(double tx, double ty, Rcpp::IntegerVector ap_seq);
RcppExport SEXP _hexify_cpp_hex_quantify_ap34(SEXP txSEXP, SEXP tySEXP, SEXP ap_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ap_seq(ap_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_quantify_ap34(tx, ty, ap_seq));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_center_ap34
Rcpp::NumericVector cpp_hex_center_ap34(double i, double j, Rcpp::IntegerVector ap_seq);
RcppExport SEXP _hexify_cpp_hex_center_ap34(SEXP iSEXP, SEXP jSEXP, SEXP ap_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ap_seq(ap_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_center_ap34(i, j, ap_seq));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_corners_ap34
Rcpp::List cpp_hex_corners_ap34(double i, double j, Rcpp::IntegerVector ap_seq, double hex_radius);
RcppExport SEXP _hexify_cpp_hex_corners_ap34(SEXP iSEXP, SEXP jSEXP, SEXP ap_seqSEXP, SEXP hex_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ap_seq(ap_seqSEXP);
    Rcpp::traits::input_parameter< double >::type hex_radius(hex_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_corners_ap34(i, j, ap_seq, hex_radius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_cell_ap34
Rcpp::NumericVector cpp_lonlat_to_cell_ap34(double lon_deg, double lat_deg, Rcpp::IntegerVector ap_seq);
RcppExport SEXP _hexify_cpp_lonlat_to_cell_ap34(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP ap_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ap_seq(ap_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_cell_ap34(lon_deg, lat_deg, ap_seq));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_lonlat_ap34
Rcpp::NumericVector cpp_cell_to_lonlat_ap34(int face, double i, double j, Rcpp::IntegerVector ap_seq);
RcppExport SEXP _hexify_cpp_cell_to_lonlat_ap34(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP ap_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ap_seq(ap_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_lonlat_ap34(face, i, j, ap_seq));
    return rcpp_result_gen;
END_RCPP
}
// cpp_test_roundtrip_ap3
bool cpp_test_roundtrip_ap3(double tx, double ty, int resolution);
RcppExport SEXP _hexify_cpp_test_roundtrip_ap3(SEXP txSEXP, SEXP tySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_test_roundtrip_ap3(tx, ty, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_test_roundtrip_ap34
bool cpp_test_roundtrip_ap34(double tx, double ty, Rcpp::IntegerVector ap_seq);
RcppExport SEXP _hexify_cpp_test_roundtrip_ap34(SEXP txSEXP, SEXP tySEXP, SEXP ap_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ap_seq(ap_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_test_roundtrip_ap34(tx, ty, ap_seq));
    return rcpp_result_gen;
END_RCPP
}
// cpp_test_roundtrip_ap4
bool cpp_test_roundtrip_ap4(double tx, double ty, int resolution);
RcppExport SEXP _hexify_cpp_test_roundtrip_ap4(SEXP txSEXP, SEXP tySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_test_roundtrip_ap4(tx, ty, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_test_roundtrip_ap7
bool cpp_test_roundtrip_ap7(double tx, double ty, int resolution);
RcppExport SEXP _hexify_cpp_test_roundtrip_ap7(SEXP txSEXP, SEXP tySEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_test_roundtrip_ap7(tx, ty, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_batch_test_roundtrip_ap3
Rcpp::List cpp_batch_test_roundtrip_ap3(Rcpp::NumericVector tx_vec, Rcpp::NumericVector ty_vec, int resolution);
RcppExport SEXP _hexify_cpp_batch_test_roundtrip_ap3(SEXP tx_vecSEXP, SEXP ty_vecSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tx_vec(tx_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ty_vec(ty_vecSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_batch_test_roundtrip_ap3(tx_vec, ty_vec, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_batch_test_roundtrip_ap4
List cpp_batch_test_roundtrip_ap4(NumericVector tx_vec, NumericVector ty_vec, int resolution);
RcppExport SEXP _hexify_cpp_batch_test_roundtrip_ap4(SEXP tx_vecSEXP, SEXP ty_vecSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tx_vec(tx_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty_vec(ty_vecSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_batch_test_roundtrip_ap4(tx_vec, ty_vec, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_batch_test_roundtrip_ap7
List cpp_batch_test_roundtrip_ap7(NumericVector tx_vec, NumericVector ty_vec, int resolution);
RcppExport SEXP _hexify_cpp_batch_test_roundtrip_ap7(SEXP tx_vecSEXP, SEXP ty_vecSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tx_vec(tx_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty_vec(ty_vecSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_batch_test_roundtrip_ap7(tx_vec, ty_vec, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cell_to_index
std::string cpp_cell_to_index(int face, double i, double j, int resolution, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_cell_to_index(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cell_to_index(face, i, j, resolution, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_index_to_cell
Rcpp::List cpp_index_to_cell(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_index_to_cell(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_index_to_cell(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_parent_index
std::string cpp_get_parent_index(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_get_parent_index(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_parent_index(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_children_indices
Rcpp::StringVector cpp_get_children_indices(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_get_children_indices(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_children_indices(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_index_resolution
int cpp_get_index_resolution(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_get_index_resolution(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_index_resolution(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compare_indices
int cpp_compare_indices(std::string idx1, std::string idx2);
RcppExport SEXP _hexify_cpp_compare_indices(SEXP idx1SEXP, SEXP idx2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type idx1(idx1SEXP);
    Rcpp::traits::input_parameter< std::string >::type idx2(idx2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compare_indices(idx1, idx2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_is_valid_index_type
bool cpp_is_valid_index_type(int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_is_valid_index_type(SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_is_valid_index_type(aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_default_index_type
std::string cpp_get_default_index_type(int aperture);
RcppExport SEXP _hexify_cpp_get_default_index_type(SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_default_index_type(aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_index_ap3
std::string cpp_lonlat_to_index_ap3(double lon_deg, double lat_deg, int resolution, std::string index_type);
RcppExport SEXP _hexify_cpp_lonlat_to_index_ap3(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_index_ap3(lon_deg, lat_deg, resolution, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_index_ap4
std::string cpp_lonlat_to_index_ap4(double lon_deg, double lat_deg, int resolution, std::string index_type);
RcppExport SEXP _hexify_cpp_lonlat_to_index_ap4(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_index_ap4(lon_deg, lat_deg, resolution, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_index_ap7
std::string cpp_lonlat_to_index_ap7(double lon_deg, double lat_deg, int resolution, std::string index_type);
RcppExport SEXP _hexify_cpp_lonlat_to_index_ap7(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_index_ap7(lon_deg, lat_deg, resolution, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_index
std::string cpp_lonlat_to_index(double lon_deg, double lat_deg, int resolution, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_lonlat_to_index(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP resolutionSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_index(lon_deg, lat_deg, resolution, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_index_to_lonlat
Rcpp::NumericVector cpp_index_to_lonlat(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_cpp_index_to_lonlat(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_index_to_lonlat(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cell_to_index
std::string cell_to_index(int face, Rcpp::NumericVector i, Rcpp::NumericVector j, int resolution, int aperture, std::string index_type);
RcppExport SEXP _hexify_cell_to_index(SEXP faceSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cell_to_index(face, i, j, resolution, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// index_to_cell
Rcpp::List index_to_cell(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_index_to_cell(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(index_to_cell(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// get_parent_index
std::string get_parent_index(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_get_parent_index(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_parent_index(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// get_children_indices
std::vector<std::string> get_children_indices(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_get_children_indices(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_children_indices(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// get_index_resolution
int get_index_resolution(std::string index, int aperture, std::string index_type);
RcppExport SEXP _hexify_get_index_resolution(SEXP indexSEXP, SEXP apertureSEXP, SEXP index_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< std::string >::type index_type(index_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_index_resolution(index, aperture, index_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_z7_canonical_form
std::string cpp_z7_canonical_form(std::string index, int max_iterations);
RcppExport SEXP _hexify_cpp_z7_canonical_form(SEXP indexSEXP, SEXP max_iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_z7_canonical_form(index, max_iterations));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_index_z3_quantize_digits
List cpp_hex_index_z3_quantize_digits(double tx, double ty, int eff_res, double center_thr, LogicalVector flip_classes);
RcppExport SEXP _hexify_cpp_hex_index_z3_quantize_digits(SEXP txSEXP, SEXP tySEXP, SEXP eff_resSEXP, SEXP center_thrSEXP, SEXP flip_classesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< int >::type eff_res(eff_resSEXP);
    Rcpp::traits::input_parameter< double >::type center_thr(center_thrSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type flip_classes(flip_classesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_index_z3_quantize_digits(tx, ty, eff_res, center_thr, flip_classes));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_index_z3_center
List cpp_hex_index_z3_center(IntegerVector d, LogicalVector flip_classes);
RcppExport SEXP _hexify_cpp_hex_index_z3_center(SEXP dSEXP, SEXP flip_classesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type flip_classes(flip_classesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_index_z3_center(d, flip_classes));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_index_z3_corners
List cpp_hex_index_z3_corners(IntegerVector digs, LogicalVector flip_classes, double hex_radius);
RcppExport SEXP _hexify_cpp_hex_index_z3_corners(SEXP digsSEXP, SEXP flip_classesSEXP, SEXP hex_radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type digs(digsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type flip_classes(flip_classesSEXP);
    Rcpp::traits::input_parameter< double >::type hex_radius(hex_radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_index_z3_corners(digs, flip_classes, hex_radius));
    return rcpp_result_gen;
END_RCPP
}
// cpp_build_icosa
void cpp_build_icosa(double vert0_lon_deg, double vert0_lat_deg, double azimuth_deg);
RcppExport SEXP _hexify_cpp_build_icosa(SEXP vert0_lon_degSEXP, SEXP vert0_lat_degSEXP, SEXP azimuth_degSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type vert0_lon_deg(vert0_lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type vert0_lat_deg(vert0_lat_degSEXP);
    Rcpp::traits::input_parameter< double >::type azimuth_deg(azimuth_degSEXP);
    cpp_build_icosa(vert0_lon_deg, vert0_lat_deg, azimuth_deg);
    return R_NilValue;
END_RCPP
}
// cpp_which_face
int cpp_which_face(double lon_deg, double lat_deg);
RcppExport SEXP _hexify_cpp_which_face(SEXP lon_degSEXP, SEXP lat_degSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_which_face(lon_deg, lat_deg));
    return rcpp_result_gen;
END_RCPP
}
// cpp_face_centers
DataFrame cpp_face_centers();
RcppExport SEXP _hexify_cpp_face_centers() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_face_centers());
    return rcpp_result_gen;
END_RCPP
}
// cpp_snyder_forward
NumericVector cpp_snyder_forward(double lon_deg, double lat_deg);
RcppExport SEXP _hexify_cpp_snyder_forward(SEXP lon_degSEXP, SEXP lat_degSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_snyder_forward(lon_deg, lat_deg));
    return rcpp_result_gen;
END_RCPP
}
// cpp_project_to_tx_ty
NumericVector cpp_project_to_tx_ty(int face, double lon_deg, double lat_deg);
RcppExport SEXP _hexify_cpp_project_to_tx_ty(SEXP faceSEXP, SEXP lon_degSEXP, SEXP lat_degSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_project_to_tx_ty(face, lon_deg, lat_deg));
    return rcpp_result_gen;
END_RCPP
}
// cpp_snyder_inv_set_precision
void cpp_snyder_inv_set_precision(std::string mode, Rcpp::Nullable<double> tol, Rcpp::Nullable<int> max_iters);
RcppExport SEXP _hexify_cpp_snyder_inv_set_precision(SEXP modeSEXP, SEXP tolSEXP, SEXP max_itersSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type max_iters(max_itersSEXP);
    cpp_snyder_inv_set_precision(mode, tol, max_iters);
    return R_NilValue;
END_RCPP
}
// cpp_snyder_inv_get_precision
Rcpp::NumericVector cpp_snyder_inv_get_precision();
RcppExport SEXP _hexify_cpp_snyder_inv_get_precision() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_snyder_inv_get_precision());
    return rcpp_result_gen;
END_RCPP
}
// cpp_snyder_inv_set_verbose
void cpp_snyder_inv_set_verbose(bool v);
RcppExport SEXP _hexify_cpp_snyder_inv_set_verbose(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type v(vSEXP);
    cpp_snyder_inv_set_verbose(v);
    return R_NilValue;
END_RCPP
}
// cpp_snyder_inv_get_stats_and_reset
Rcpp::IntegerVector cpp_snyder_inv_get_stats_and_reset();
RcppExport SEXP _hexify_cpp_snyder_inv_get_stats_and_reset() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_snyder_inv_get_stats_and_reset());
    return rcpp_result_gen;
END_RCPP
}
// cpp_face_xy_to_ll
Rcpp::NumericVector cpp_face_xy_to_ll(double x, double y, int face, Rcpp::Nullable<double> tol, Rcpp::Nullable<int> max_iters);
RcppExport SEXP _hexify_cpp_face_xy_to_ll(SEXP xSEXP, SEXP ySEXP, SEXP faceSEXP, SEXP tolSEXP, SEXP max_itersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type max_iters(max_itersSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_face_xy_to_ll(x, y, face, tol, max_iters));
    return rcpp_result_gen;
END_RCPP
}
// cpp_icosa_face_params
Rcpp::NumericVector cpp_icosa_face_params(int face);
RcppExport SEXP _hexify_cpp_icosa_face_params(SEXP faceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type face(faceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_icosa_face_params(face));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hex_index_face_to_lonlat
Rcpp::NumericVector cpp_hex_index_face_to_lonlat(double x, double y, double cen_lat, double cen_lon, double dazh, bool degrees, Rcpp::Nullable<double> tol, Rcpp::Nullable<int> max_iters);
RcppExport SEXP _hexify_cpp_hex_index_face_to_lonlat(SEXP xSEXP, SEXP ySEXP, SEXP cen_latSEXP, SEXP cen_lonSEXP, SEXP dazhSEXP, SEXP degreesSEXP, SEXP tolSEXP, SEXP max_itersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type cen_lat(cen_latSEXP);
    Rcpp::traits::input_parameter< double >::type cen_lon(cen_lonSEXP);
    Rcpp::traits::input_parameter< double >::type dazh(dazhSEXP);
    Rcpp::traits::input_parameter< bool >::type degrees(degreesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type max_iters(max_itersSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hex_index_face_to_lonlat(x, y, cen_lat, cen_lon, dazh, degrees, tol, max_iters));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_seqnum
NumericVector cpp_lonlat_to_seqnum(NumericVector lon, NumericVector lat, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_lonlat_to_seqnum(SEXP lonSEXP, SEXP latSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_seqnum(lon, lat, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_seqnum_to_lonlat
DataFrame cpp_seqnum_to_lonlat(NumericVector seqnum, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_seqnum_to_lonlat(SEXP seqnumSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type seqnum(seqnumSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_seqnum_to_lonlat(seqnum, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_seqnum_to_cell_info
List cpp_seqnum_to_cell_info(NumericVector seqnum, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_seqnum_to_cell_info(SEXP seqnumSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type seqnum(seqnumSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_seqnum_to_cell_info(seqnum, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_decode_z7
DataFrame cpp_decode_z7(std::string index_body, int aperture);
RcppExport SEXP _hexify_cpp_decode_z7(SEXP index_bodySEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type index_body(index_bodySEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_decode_z7(index_body, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_projtri_to_q2di
Rcpp::List cpp_projtri_to_q2di(int tnum, double tx, double ty, int aperture, int resolution);
RcppExport SEXP _hexify_cpp_projtri_to_q2di(SEXP tnumSEXP, SEXP txSEXP, SEXP tySEXP, SEXP apertureSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type tnum(tnumSEXP);
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_projtri_to_q2di(tnum, tx, ty, aperture, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_projtri_to_q2dd
Rcpp::List cpp_projtri_to_q2dd(int tnum, double tx, double ty);
RcppExport SEXP _hexify_cpp_projtri_to_q2dd(SEXP tnumSEXP, SEXP txSEXP, SEXP tySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type tnum(tnumSEXP);
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_projtri_to_q2dd(tnum, tx, ty));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_q2di
Rcpp::List cpp_lonlat_to_q2di(double lon_deg, double lat_deg, int aperture, int resolution);
RcppExport SEXP _hexify_cpp_lonlat_to_q2di(SEXP lon_degSEXP, SEXP lat_degSEXP, SEXP apertureSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lon_deg(lon_degSEXP);
    Rcpp::traits::input_parameter< double >::type lat_deg(lat_degSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_q2di(lon_deg, lat_deg, aperture, resolution));
    return rcpp_result_gen;
END_RCPP
}
// cpp_q2di_to_seqnum
NumericVector cpp_q2di_to_seqnum(IntegerVector quad, NumericVector i, NumericVector j, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_q2di_to_seqnum(SEXP quadSEXP, SEXP iSEXP, SEXP jSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type quad(quadSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_q2di_to_seqnum(quad, i, j, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lonlat_to_seqnum_dggrid
NumericVector cpp_lonlat_to_seqnum_dggrid(NumericVector lon, NumericVector lat, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_lonlat_to_seqnum_dggrid(SEXP lonSEXP, SEXP latSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lonlat_to_seqnum_dggrid(lon, lat, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}
// cpp_seqnum_to_lonlat_dggrid
DataFrame cpp_seqnum_to_lonlat_dggrid(NumericVector seqnum, int resolution, int aperture);
RcppExport SEXP _hexify_cpp_seqnum_to_lonlat_dggrid(SEXP seqnumSEXP, SEXP resolutionSEXP, SEXP apertureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type seqnum(seqnumSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type aperture(apertureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_seqnum_to_lonlat_dggrid(seqnum, resolution, aperture));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hexify_cpp_hex_quantify_ap3", (DL_FUNC) &_hexify_cpp_hex_quantify_ap3, 3},
    {"_hexify_cpp_hex_center_ap3", (DL_FUNC) &_hexify_cpp_hex_center_ap3, 3},
    {"_hexify_cpp_hex_corners_ap3", (DL_FUNC) &_hexify_cpp_hex_corners_ap3, 4},
    {"_hexify_cpp_lonlat_to_cell_ap3", (DL_FUNC) &_hexify_cpp_lonlat_to_cell_ap3, 3},
    {"_hexify_cpp_cell_to_lonlat_ap3", (DL_FUNC) &_hexify_cpp_cell_to_lonlat_ap3, 4},
    {"_hexify_cpp_hex_quantify_ap4", (DL_FUNC) &_hexify_cpp_hex_quantify_ap4, 3},
    {"_hexify_cpp_hex_center_ap4", (DL_FUNC) &_hexify_cpp_hex_center_ap4, 3},
    {"_hexify_cpp_hex_corners_ap4", (DL_FUNC) &_hexify_cpp_hex_corners_ap4, 4},
    {"_hexify_cpp_lonlat_to_cell_ap4", (DL_FUNC) &_hexify_cpp_lonlat_to_cell_ap4, 3},
    {"_hexify_cpp_cell_to_lonlat_ap4", (DL_FUNC) &_hexify_cpp_cell_to_lonlat_ap4, 4},
    {"_hexify_cpp_hex_quantify_ap7", (DL_FUNC) &_hexify_cpp_hex_quantify_ap7, 3},
    {"_hexify_cpp_hex_center_ap7", (DL_FUNC) &_hexify_cpp_hex_center_ap7, 3},
    {"_hexify_cpp_hex_corners_ap7", (DL_FUNC) &_hexify_cpp_hex_corners_ap7, 4},
    {"_hexify_cpp_lonlat_to_cell_ap7", (DL_FUNC) &_hexify_cpp_lonlat_to_cell_ap7, 3},
    {"_hexify_cpp_cell_to_lonlat_ap7", (DL_FUNC) &_hexify_cpp_cell_to_lonlat_ap7, 4},
    {"_hexify_cpp_hex_quantify_ap34", (DL_FUNC) &_hexify_cpp_hex_quantify_ap34, 3},
    {"_hexify_cpp_hex_center_ap34", (DL_FUNC) &_hexify_cpp_hex_center_ap34, 3},
    {"_hexify_cpp_hex_corners_ap34", (DL_FUNC) &_hexify_cpp_hex_corners_ap34, 4},
    {"_hexify_cpp_lonlat_to_cell_ap34", (DL_FUNC) &_hexify_cpp_lonlat_to_cell_ap34, 3},
    {"_hexify_cpp_cell_to_lonlat_ap34", (DL_FUNC) &_hexify_cpp_cell_to_lonlat_ap34, 4},
    {"_hexify_cpp_test_roundtrip_ap3", (DL_FUNC) &_hexify_cpp_test_roundtrip_ap3, 3},
    {"_hexify_cpp_test_roundtrip_ap34", (DL_FUNC) &_hexify_cpp_test_roundtrip_ap34, 3},
    {"_hexify_cpp_test_roundtrip_ap4", (DL_FUNC) &_hexify_cpp_test_roundtrip_ap4, 3},
    {"_hexify_cpp_test_roundtrip_ap7", (DL_FUNC) &_hexify_cpp_test_roundtrip_ap7, 3},
    {"_hexify_cpp_batch_test_roundtrip_ap3", (DL_FUNC) &_hexify_cpp_batch_test_roundtrip_ap3, 3},
    {"_hexify_cpp_batch_test_roundtrip_ap4", (DL_FUNC) &_hexify_cpp_batch_test_roundtrip_ap4, 3},
    {"_hexify_cpp_batch_test_roundtrip_ap7", (DL_FUNC) &_hexify_cpp_batch_test_roundtrip_ap7, 3},
    {"_hexify_cpp_cell_to_index", (DL_FUNC) &_hexify_cpp_cell_to_index, 6},
    {"_hexify_cpp_index_to_cell", (DL_FUNC) &_hexify_cpp_index_to_cell, 3},
    {"_hexify_cpp_get_parent_index", (DL_FUNC) &_hexify_cpp_get_parent_index, 3},
    {"_hexify_cpp_get_children_indices", (DL_FUNC) &_hexify_cpp_get_children_indices, 3},
    {"_hexify_cpp_get_index_resolution", (DL_FUNC) &_hexify_cpp_get_index_resolution, 3},
    {"_hexify_cpp_compare_indices", (DL_FUNC) &_hexify_cpp_compare_indices, 2},
    {"_hexify_cpp_is_valid_index_type", (DL_FUNC) &_hexify_cpp_is_valid_index_type, 2},
    {"_hexify_cpp_get_default_index_type", (DL_FUNC) &_hexify_cpp_get_default_index_type, 1},
    {"_hexify_cpp_lonlat_to_index_ap3", (DL_FUNC) &_hexify_cpp_lonlat_to_index_ap3, 4},
    {"_hexify_cpp_lonlat_to_index_ap4", (DL_FUNC) &_hexify_cpp_lonlat_to_index_ap4, 4},
    {"_hexify_cpp_lonlat_to_index_ap7", (DL_FUNC) &_hexify_cpp_lonlat_to_index_ap7, 4},
    {"_hexify_cpp_lonlat_to_index", (DL_FUNC) &_hexify_cpp_lonlat_to_index, 5},
    {"_hexify_cpp_index_to_lonlat", (DL_FUNC) &_hexify_cpp_index_to_lonlat, 3},
    {"_hexify_cell_to_index", (DL_FUNC) &_hexify_cell_to_index, 6},
    {"_hexify_index_to_cell", (DL_FUNC) &_hexify_index_to_cell, 3},
    {"_hexify_get_parent_index", (DL_FUNC) &_hexify_get_parent_index, 3},
    {"_hexify_get_children_indices", (DL_FUNC) &_hexify_get_children_indices, 3},
    {"_hexify_get_index_resolution", (DL_FUNC) &_hexify_get_index_resolution, 3},
    {"_hexify_cpp_z7_canonical_form", (DL_FUNC) &_hexify_cpp_z7_canonical_form, 2},
    {"_hexify_cpp_hex_index_z3_quantize_digits", (DL_FUNC) &_hexify_cpp_hex_index_z3_quantize_digits, 5},
    {"_hexify_cpp_hex_index_z3_center", (DL_FUNC) &_hexify_cpp_hex_index_z3_center, 2},
    {"_hexify_cpp_hex_index_z3_corners", (DL_FUNC) &_hexify_cpp_hex_index_z3_corners, 3},
    {"_hexify_cpp_build_icosa", (DL_FUNC) &_hexify_cpp_build_icosa, 3},
    {"_hexify_cpp_which_face", (DL_FUNC) &_hexify_cpp_which_face, 2},
    {"_hexify_cpp_face_centers", (DL_FUNC) &_hexify_cpp_face_centers, 0},
    {"_hexify_cpp_snyder_forward", (DL_FUNC) &_hexify_cpp_snyder_forward, 2},
    {"_hexify_cpp_project_to_tx_ty", (DL_FUNC) &_hexify_cpp_project_to_tx_ty, 3},
    {"_hexify_cpp_snyder_inv_set_precision", (DL_FUNC) &_hexify_cpp_snyder_inv_set_precision, 3},
    {"_hexify_cpp_snyder_inv_get_precision", (DL_FUNC) &_hexify_cpp_snyder_inv_get_precision, 0},
    {"_hexify_cpp_snyder_inv_set_verbose", (DL_FUNC) &_hexify_cpp_snyder_inv_set_verbose, 1},
    {"_hexify_cpp_snyder_inv_get_stats_and_reset", (DL_FUNC) &_hexify_cpp_snyder_inv_get_stats_and_reset, 0},
    {"_hexify_cpp_face_xy_to_ll", (DL_FUNC) &_hexify_cpp_face_xy_to_ll, 5},
    {"_hexify_cpp_icosa_face_params", (DL_FUNC) &_hexify_cpp_icosa_face_params, 1},
    {"_hexify_cpp_hex_index_face_to_lonlat", (DL_FUNC) &_hexify_cpp_hex_index_face_to_lonlat, 8},
    {"_hexify_cpp_lonlat_to_seqnum", (DL_FUNC) &_hexify_cpp_lonlat_to_seqnum, 4},
    {"_hexify_cpp_seqnum_to_lonlat", (DL_FUNC) &_hexify_cpp_seqnum_to_lonlat, 3},
    {"_hexify_cpp_seqnum_to_cell_info", (DL_FUNC) &_hexify_cpp_seqnum_to_cell_info, 3},
    {"_hexify_cpp_decode_z7", (DL_FUNC) &_hexify_cpp_decode_z7, 2},
    {"_hexify_cpp_projtri_to_q2di", (DL_FUNC) &_hexify_cpp_projtri_to_q2di, 5},
    {"_hexify_cpp_projtri_to_q2dd", (DL_FUNC) &_hexify_cpp_projtri_to_q2dd, 3},
    {"_hexify_cpp_lonlat_to_q2di", (DL_FUNC) &_hexify_cpp_lonlat_to_q2di, 4},
    {"_hexify_cpp_q2di_to_seqnum", (DL_FUNC) &_hexify_cpp_q2di_to_seqnum, 5},
    {"_hexify_cpp_lonlat_to_seqnum_dggrid", (DL_FUNC) &_hexify_cpp_lonlat_to_seqnum_dggrid, 4},
    {"_hexify_cpp_seqnum_to_lonlat_dggrid", (DL_FUNC) &_hexify_cpp_seqnum_to_lonlat_dggrid, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_hexify(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
