# R/hex_distance.R
# Grid distance between hex cells

#' Cell-lattice generator of a grid
#'
#' The cells of a quad occupy a sublattice of the substrate their IDs are
#' packed on, generated by one Eisenstein integer `a + b*omega` written in the
#' `(i, j)` coordinates `grid_quad_ij()` returns. Aperture 4, aperture 3's even
#' resolutions and aperture 7's surrogates all sit on the substrate itself, so
#' the generator is `1`; aperture 3's odd resolutions carry the 30-degree
#' lattice whose generator is `2 + omega`. A mixed sequence reads its own from
#' the form the sequence builds.
#'
#' @param g A HexGridInfo object
#' @return Numeric vector `c(a, b)`
#' @noRd
grid_cell_lattice <- function(g) {
  if (is_mixed_aperture(g@aperture)) {
    return(cpp_cell_lattice_generator_seq(grid_ap_seq(g)))
  }
  cpp_cell_lattice_generator(aperture_to_int(g@aperture), g@resolution)
}

#' Cell steps between two cells of one quad
#'
#' Dividing the substrate difference by the cell-lattice generator writes it in
#' cell steps, where the six neighbours are the six units of the Eisenstein
#' integers and the distance is the axial hex distance
#' `max(|di|, |dj|, |di - dj|)`.
#'
#' @param di,dj Substrate differences
#' @param generator The grid's cell-lattice generator, `c(a, b)`
#' @return Numeric vector of hop counts
#' @noRd
quad_ij_hops <- function(di, dj, generator) {
  a <- generator[1]
  b <- generator[2]
  norm <- a * a - a * b + b * b

  # (di + dj*omega) times the conjugate (a - b) - b*omega, then divided by the
  # norm: exact, because both cells lie on the sublattice.
  qi <- (di * (a - b) + dj * b) / norm
  qj <- (dj * a - di * b) / norm

  pmax(abs(qi), abs(qj), abs(qi - qj))
}

#' Hops from one cell to a set of targets, by breadth-first search
#'
#' @param source One cell ID
#' @param targets Cell IDs to reach
#' @param g HexGridInfo object
#' @param max_search Rings to expand before giving up
#' @return Numeric vector of hop counts, `NA` where a target was not reached
#' @noRd
isea_bfs_hops <- function(source, targets, g, max_search = 100L) {
  out <- rep(NA_real_, length(targets))
  wanted <- unique(targets)
  found <- stats::setNames(rep(NA_real_, length(wanted)), as.character(wanted))
  found[as.character(source)] <- 0

  visited <- source
  frontier <- source

  for (dist in seq_len(max_search)) {
    if (!anyNA(found)) break
    frontier <- setdiff(unique(unlist(
      grid_neighbors_isea(frontier, g)
    )), visited)
    if (length(frontier) == 0) break

    visited <- c(visited, frontier)
    reached <- as.character(frontier)
    reached <- reached[reached %in% names(found)]
    found[reached] <- dist
  }

  out[] <- found[as.character(targets)]
  out
}

#' Grid Distance Between Cells
#'
#' Computes the grid distance (minimum number of hops) between pairs
#' of hexagonal cells. This is a discrete distance measured in cell steps,
#' not a geodesic distance.
#'
#' @param cell_a,cell_b Cell IDs. Must be the same length (pairs) or one
#'   of them length 1 (broadcast). For H3 grids, character vectors.
#'   For ISEA grids, numeric vectors.
#' @param grid A HexGridInfo or HexData object specifying the grid.
#'
#' @return An integer vector of grid distances. `NA` where the distance
#'   cannot be computed (e.g., pentagon path issues in H3).
#'
#' @details
#' **H3 backend:** Uses the vendored H3 `gridDistance` function.
#' Returns the exact shortest path length in cell hops.
#'
#' **ISEA backend:** Cells on the same quad are counted in the quad's own cell
#' lattice, where the six neighbours are one step away and the distance is the
#' axial hex distance `max(|di|, |dj|, |di - dj|)`. The lattice is not always
#' the substrate the cell IDs are packed on -- at aperture 3's odd resolutions
#' one substrate point in three is a cell -- so the difference is divided by the
#' lattice generator first. Cross-quad distances use breadth-first search over
#' [get_neighbors()] and return `NA` beyond a hundred rings.
#'
#' For geodesic (geographic) distances between cell centers, convert to
#' lon/lat with [cell_to_lonlat()] and use `sf::st_distance()`.
#'
#' @seealso [get_neighbors()] for finding cells within a given distance,
#'   [cell_to_lonlat()] for geographic coordinates
#'
#' @export
#' @examples
#' \donttest{
#' # H3 grid distance
#' g <- hex_grid(resolution = 5, type = "h3")
#' a <- lonlat_to_cell(10, 50, g)
#' b <- lonlat_to_cell(10.1, 50.1, g)
#' hex_distance(a, b, g)
#' }
#'
#' # ISEA: neighbouring cells are one hop apart
#' g <- hex_grid(resolution = 3, aperture = 3)
#' a <- lonlat_to_cell(10, 50, g)
#' hex_distance(a, get_neighbors(a, g)[[1]], g)
hex_distance <- function(cell_a, cell_b, grid) {
  g <- extract_grid(grid)

  # Recycle to equal length
  n <- max(length(cell_a), length(cell_b))
  cell_a <- rep_len(cell_a, n)
  cell_b <- rep_len(cell_b, n)

  if (is_h3_grid(g)) {
    return(cpp_h3_gridDistance(as.character(cell_a), as.character(cell_b)))
  }

  cell_a <- as.numeric(cell_a)
  cell_b <- as.numeric(cell_b)

  result <- rep(NA_real_, n)
  known <- !is.na(cell_a) & !is.na(cell_b)
  if (!any(known)) {
    return(as.integer(result))
  }

  info_a <- grid_quad_ij(cell_a[known], g)
  info_b <- grid_quad_ij(cell_b[known], g)

  # Same quad: read the difference in the quad's cell lattice
  on_one_quad <- info_a$quad == info_b$quad
  same <- known
  same[known] <- on_one_quad
  if (any(on_one_quad)) {
    result[same] <- quad_ij_hops(info_a$i[on_one_quad] - info_b$i[on_one_quad],
                                 info_a$j[on_one_quad] - info_b$j[on_one_quad],
                                 grid_cell_lattice(g))
  }

  # Cross-quad: breadth-first search, one expansion per distinct source
  cross <- known & !same
  if (any(cross)) {
    for (source in unique(cell_a[cross])) {
      from <- cross & cell_a == source
      result[from] <- isea_bfs_hops(source, cell_b[from], g)
    }
  }

  as.integer(result)
}
