# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_globe_faces <- function(icosa, max_len) {
    .Call(`_hexify_cpp_globe_faces`, icosa, max_len)
}

cpp_globe_projection <- function(icosa) {
    .Call(`_hexify_cpp_globe_projection`, icosa)
}

cpp_globe_polygons <- function(icosa, polygons, max_len) {
    .Call(`_hexify_cpp_globe_polygons`, icosa, polygons, max_len)
}

cpp_sphere_paths_on_faces <- function(icosa, lon, lat, path, max_angle) {
    .Call(`_hexify_cpp_sphere_paths_on_faces`, icosa, lon, lat, path, max_angle)
}

cpp_base64_buffer <- function(x, type) {
    .Call(`_hexify_cpp_base64_buffer`, x, type)
}

cpp_hex_quantize_ap3 <- function(icosa_triangle_x, icosa_triangle_y, resolution) {
    .Call(`_hexify_cpp_hex_quantize_ap3`, icosa_triangle_x, icosa_triangle_y, resolution)
}

cpp_hex_center_ap3 <- function(i, j, resolution) {
    .Call(`_hexify_cpp_hex_center_ap3`, i, j, resolution)
}

cpp_hex_corners_ap3 <- function(i, j, resolution, hex_radius = 1.0) {
    .Call(`_hexify_cpp_hex_corners_ap3`, i, j, resolution, hex_radius)
}

cpp_lonlat_to_cell_ap3 <- function(lon_deg, lat_deg, resolution) {
    .Call(`_hexify_cpp_lonlat_to_cell_ap3`, lon_deg, lat_deg, resolution)
}

cpp_cell_to_lonlat_ap3 <- function(face, i, j, resolution) {
    .Call(`_hexify_cpp_cell_to_lonlat_ap3`, face, i, j, resolution)
}

cpp_hex_quantize_ap4 <- function(icosa_triangle_x, icosa_triangle_y, resolution) {
    .Call(`_hexify_cpp_hex_quantize_ap4`, icosa_triangle_x, icosa_triangle_y, resolution)
}

cpp_hex_center_ap4 <- function(i, j, resolution) {
    .Call(`_hexify_cpp_hex_center_ap4`, i, j, resolution)
}

cpp_hex_corners_ap4 <- function(i, j, resolution, hex_radius = 1.0) {
    .Call(`_hexify_cpp_hex_corners_ap4`, i, j, resolution, hex_radius)
}

cpp_lonlat_to_cell_ap4 <- function(lon_deg, lat_deg, resolution) {
    .Call(`_hexify_cpp_lonlat_to_cell_ap4`, lon_deg, lat_deg, resolution)
}

cpp_cell_to_lonlat_ap4 <- function(face, i, j, resolution) {
    .Call(`_hexify_cpp_cell_to_lonlat_ap4`, face, i, j, resolution)
}

cpp_hex_quantize_ap7 <- function(icosa_triangle_x, icosa_triangle_y, resolution) {
    .Call(`_hexify_cpp_hex_quantize_ap7`, icosa_triangle_x, icosa_triangle_y, resolution)
}

cpp_hex_center_ap7 <- function(i, j, resolution) {
    .Call(`_hexify_cpp_hex_center_ap7`, i, j, resolution)
}

cpp_hex_corners_ap7 <- function(i, j, resolution, hex_radius = 1.0) {
    .Call(`_hexify_cpp_hex_corners_ap7`, i, j, resolution, hex_radius)
}

cpp_lonlat_to_cell_ap7 <- function(lon_deg, lat_deg, resolution) {
    .Call(`_hexify_cpp_lonlat_to_cell_ap7`, lon_deg, lat_deg, resolution)
}

cpp_cell_to_lonlat_ap7 <- function(face, i, j, resolution) {
    .Call(`_hexify_cpp_cell_to_lonlat_ap7`, face, i, j, resolution)
}

cpp_hex_quantize_mixed <- function(icosa_triangle_x, icosa_triangle_y, ap_seq) {
    .Call(`_hexify_cpp_hex_quantize_mixed`, icosa_triangle_x, icosa_triangle_y, ap_seq)
}

cpp_hex_center_mixed <- function(i, j, ap_seq) {
    .Call(`_hexify_cpp_hex_center_mixed`, i, j, ap_seq)
}

cpp_hex_corners_mixed <- function(i, j, ap_seq, hex_radius = 1.0) {
    .Call(`_hexify_cpp_hex_corners_mixed`, i, j, ap_seq, hex_radius)
}

cpp_lonlat_to_cell_mixed <- function(lon_deg, lat_deg, ap_seq) {
    .Call(`_hexify_cpp_lonlat_to_cell_mixed`, lon_deg, lat_deg, ap_seq)
}

cpp_cell_to_lonlat_mixed <- function(face, i, j, ap_seq) {
    .Call(`_hexify_cpp_cell_to_lonlat_mixed`, face, i, j, ap_seq)
}

cpp_test_roundtrip_ap3 <- function(icosa_triangle_x, icosa_triangle_y, resolution) {
    .Call(`_hexify_cpp_test_roundtrip_ap3`, icosa_triangle_x, icosa_triangle_y, resolution)
}

cpp_test_roundtrip_ap4 <- function(icosa_triangle_x, icosa_triangle_y, resolution) {
    .Call(`_hexify_cpp_test_roundtrip_ap4`, icosa_triangle_x, icosa_triangle_y, resolution)
}

cpp_test_roundtrip_ap7 <- function(icosa_triangle_x, icosa_triangle_y, resolution) {
    .Call(`_hexify_cpp_test_roundtrip_ap7`, icosa_triangle_x, icosa_triangle_y, resolution)
}

cpp_test_roundtrip_mixed <- function(icosa_triangle_x, icosa_triangle_y, ap_seq) {
    .Call(`_hexify_cpp_test_roundtrip_mixed`, icosa_triangle_x, icosa_triangle_y, ap_seq)
}

cpp_batch_test_roundtrip_ap3 <- function(tx_vec, ty_vec, resolution) {
    .Call(`_hexify_cpp_batch_test_roundtrip_ap3`, tx_vec, ty_vec, resolution)
}

cpp_batch_test_roundtrip_ap4 <- function(tx_vec, ty_vec, resolution) {
    .Call(`_hexify_cpp_batch_test_roundtrip_ap4`, tx_vec, ty_vec, resolution)
}

cpp_batch_test_roundtrip_ap7 <- function(tx_vec, ty_vec, resolution) {
    .Call(`_hexify_cpp_batch_test_roundtrip_ap7`, tx_vec, ty_vec, resolution)
}

cpp_icosa_tri_to_quad_ij <- function(icosa, icosa_triangle_face, icosa_triangle_x, icosa_triangle_y, aperture, resolution) {
    .Call(`_hexify_cpp_icosa_tri_to_quad_ij`, icosa, icosa_triangle_face, icosa_triangle_x, icosa_triangle_y, aperture, resolution)
}

cpp_icosa_tri_to_quad_xy <- function(icosa, icosa_triangle_face, icosa_triangle_x, icosa_triangle_y) {
    .Call(`_hexify_cpp_icosa_tri_to_quad_xy`, icosa, icosa_triangle_face, icosa_triangle_x, icosa_triangle_y)
}

cpp_quad_xy_to_icosa_tri <- function(icosa, quad, quad_x, quad_y) {
    .Call(`_hexify_cpp_quad_xy_to_icosa_tri`, icosa, quad, quad_x, quad_y)
}

cpp_quad_ij_to_xy <- function(quad, i, j, aperture, resolution) {
    .Call(`_hexify_cpp_quad_ij_to_xy`, quad, i, j, aperture, resolution)
}

cpp_lonlat_to_quad_ij <- function(icosa, lon_deg, lat_deg, aperture, resolution) {
    .Call(`_hexify_cpp_lonlat_to_quad_ij`, icosa, lon_deg, lat_deg, aperture, resolution)
}

cpp_quad_edge_dim <- function(resolution, aperture, ap_seq) {
    .Call(`_hexify_cpp_quad_edge_dim`, resolution, aperture, ap_seq)
}

cpp_cell_lattice_generator <- function(resolution, aperture, ap_seq) {
    .Call(`_hexify_cpp_cell_lattice_generator`, resolution, aperture, ap_seq)
}

cpp_quad_ij_to_cell <- function(icosa, quad, i, j, resolution, aperture, ap_seq) {
    .Call(`_hexify_cpp_quad_ij_to_cell`, icosa, quad, i, j, resolution, aperture, ap_seq)
}

cpp_mixed_parent <- function(icosa, cell_id, ap_seq, parent_seq) {
    .Call(`_hexify_cpp_mixed_parent`, icosa, cell_id, ap_seq, parent_seq)
}

cpp_lonlat_to_cell <- function(icosa, lon, lat, resolution, aperture, ap_seq) {
    .Call(`_hexify_cpp_lonlat_to_cell`, icosa, lon, lat, resolution, aperture, ap_seq)
}

cpp_cell_to_lonlat <- function(icosa, cell_id, resolution, aperture, ap_seq) {
    .Call(`_hexify_cpp_cell_to_lonlat`, icosa, cell_id, resolution, aperture, ap_seq)
}

cpp_cell_to_quad_ij <- function(icosa, cell_id, resolution, aperture, ap_seq) {
    .Call(`_hexify_cpp_cell_to_quad_ij`, icosa, cell_id, resolution, aperture, ap_seq)
}

cpp_cell_to_quad_xy <- function(icosa, cell_id, resolution, aperture) {
    .Call(`_hexify_cpp_cell_to_quad_xy`, icosa, cell_id, resolution, aperture)
}

cpp_quad_xy_to_cell <- function(icosa, quad, quad_x, quad_y, resolution, aperture) {
    .Call(`_hexify_cpp_quad_xy_to_cell`, icosa, quad, quad_x, quad_y, resolution, aperture)
}

cpp_cell_to_icosa_tri <- function(icosa, cell_id, resolution, aperture) {
    .Call(`_hexify_cpp_cell_to_icosa_tri`, icosa, cell_id, resolution, aperture)
}

cpp_quad_ij_to_icosa_tri <- function(icosa, quad, i, j, resolution, aperture) {
    .Call(`_hexify_cpp_quad_ij_to_icosa_tri`, icosa, quad, i, j, resolution, aperture)
}

cpp_cell_to_corners <- function(icosa, cell_id, resolution, aperture, ap_seq, tolerance = 0.0) {
    .Call(`_hexify_cpp_cell_to_corners`, icosa, cell_id, resolution, aperture, ap_seq, tolerance)
}

cpp_densify_great_circle <- function(rings, tolerance) {
    .Call(`_hexify_cpp_densify_great_circle`, rings, tolerance)
}

cpp_cell_solid_angle <- function(icosa, cell_id, resolution, aperture, ap_seq, tolerance) {
    .Call(`_hexify_cpp_cell_solid_angle`, icosa, cell_id, resolution, aperture, ap_seq, tolerance)
}

cpp_cell_surface_paths <- function(icosa, cell_id, resolution, aperture, ap_seq, step) {
    .Call(`_hexify_cpp_cell_surface_paths`, icosa, cell_id, resolution, aperture, ap_seq, step)
}

cpp_icosa_solid <- function(icosa) {
    .Call(`_hexify_cpp_icosa_solid`, icosa)
}

cpp_lonlat_to_face_solid <- function(icosa, face, lon, lat) {
    .Call(`_hexify_cpp_lonlat_to_face_solid`, icosa, face, lon, lat)
}

cpp_face_tri_to_solid <- function(icosa, face, tx, ty) {
    .Call(`_hexify_cpp_face_tri_to_solid`, icosa, face, tx, ty)
}

cpp_globe_frame <- function(icosa, resolution, aperture, ap_seq) {
    .Call(`_hexify_cpp_globe_frame`, icosa, resolution, aperture, ap_seq)
}

cpp_get_neighbors_isea <- function(icosa, cell_id, resolution, aperture, ap_seq) {
    .Call(`_hexify_cpp_get_neighbors_isea`, icosa, cell_id, resolution, aperture, ap_seq)
}

cpp_cell_walls <- function(icosa, cell_id, resolution, aperture, ap_seq, tolerance, walls) {
    .Call(`_hexify_cpp_cell_walls`, icosa, cell_id, resolution, aperture, ap_seq, tolerance, walls)
}

cpp_ring_walls <- function(rings, centres, neighbour_centres) {
    .Call(`_hexify_cpp_ring_walls`, rings, centres, neighbour_centres)
}

cpp_icosa_tri_to_plane <- function(icosa, icosa_triangle_face, icosa_triangle_x, icosa_triangle_y) {
    .Call(`_hexify_cpp_icosa_tri_to_plane`, icosa, icosa_triangle_face, icosa_triangle_x, icosa_triangle_y)
}

cpp_cell_to_plane <- function(icosa, cell_id, resolution, aperture) {
    .Call(`_hexify_cpp_cell_to_plane`, icosa, cell_id, resolution, aperture)
}

cpp_lonlat_to_plane <- function(icosa, lon, lat) {
    .Call(`_hexify_cpp_lonlat_to_plane`, icosa, lon, lat)
}

cpp_h3_latLngToCell <- function(lon_deg, lat_deg, resolution) {
    .Call(`_hexify_cpp_h3_latLngToCell`, lon_deg, lat_deg, resolution)
}

cpp_h3_cellToLatLng <- function(cell_ids) {
    .Call(`_hexify_cpp_h3_cellToLatLng`, cell_ids)
}

cpp_h3_isValidCell <- function(cell_ids) {
    .Call(`_hexify_cpp_h3_isValidCell`, cell_ids)
}

cpp_h3_cellToParent <- function(cell_ids, parent_res) {
    .Call(`_hexify_cpp_h3_cellToParent`, cell_ids, parent_res)
}

cpp_h3_cellToChildren <- function(cell_ids, child_res) {
    .Call(`_hexify_cpp_h3_cellToChildren`, cell_ids, child_res)
}

cpp_h3_cellToBoundary <- function(cell_ids) {
    .Call(`_hexify_cpp_h3_cellToBoundary`, cell_ids)
}

cpp_h3_polygonToCells <- function(coords, resolution, holes = NULL, flags = 2L) {
    .Call(`_hexify_cpp_h3_polygonToCells`, coords, resolution, holes, flags)
}

cpp_h3_getResolution <- function(cell_ids) {
    .Call(`_hexify_cpp_h3_getResolution`, cell_ids)
}

cpp_h3_cellAreaKm2 <- function(cell_ids) {
    .Call(`_hexify_cpp_h3_cellAreaKm2`, cell_ids)
}

cpp_h3_gridDisk <- function(cell_ids, k) {
    .Call(`_hexify_cpp_h3_gridDisk`, cell_ids, k)
}

cpp_h3_gridDiskDistances <- function(cell_ids, k) {
    .Call(`_hexify_cpp_h3_gridDiskDistances`, cell_ids, k)
}

cpp_h3_gridRingUnsafe <- function(cell_ids, k) {
    .Call(`_hexify_cpp_h3_gridRingUnsafe`, cell_ids, k)
}

cpp_h3_compactCells <- function(cell_ids) {
    .Call(`_hexify_cpp_h3_compactCells`, cell_ids)
}

cpp_h3_uncompactCells <- function(cell_ids, target_res) {
    .Call(`_hexify_cpp_h3_uncompactCells`, cell_ids, target_res)
}

cpp_h3_isPentagon <- function(cell_ids) {
    .Call(`_hexify_cpp_h3_isPentagon`, cell_ids)
}

cpp_h3_gridDistance <- function(origin, destination) {
    .Call(`_hexify_cpp_h3_gridDistance`, origin, destination)
}

cpp_h3_cell_walls <- function(cell_ids, walls) {
    .Call(`_hexify_cpp_h3_cell_walls`, cell_ids, walls)
}

cpp_cell_to_index <- function(icosa, face, i, j, resolution, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_cell_to_index`, icosa, face, i, j, resolution, aperture, index_type)
}

cpp_index_to_cell <- function(icosa, index, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_index_to_cell`, icosa, index, aperture, index_type)
}

cpp_get_parent_index <- function(index, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_get_parent_index`, index, aperture, index_type)
}

cpp_get_children_indices <- function(icosa, index, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_get_children_indices`, icosa, index, aperture, index_type)
}

cpp_get_index_resolution <- function(index, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_get_index_resolution`, index, aperture, index_type)
}

cpp_compare_indices <- function(idx1, idx2) {
    .Call(`_hexify_cpp_compare_indices`, idx1, idx2)
}

cpp_is_valid_index_type <- function(aperture, index_type) {
    .Call(`_hexify_cpp_is_valid_index_type`, aperture, index_type)
}

cpp_get_default_index_type <- function(aperture) {
    .Call(`_hexify_cpp_get_default_index_type`, aperture)
}

cpp_lonlat_to_index <- function(icosa, lon_deg, lat_deg, resolution, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_lonlat_to_index`, icosa, lon_deg, lat_deg, resolution, aperture, index_type)
}

cpp_index_to_lonlat <- function(icosa, index, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_index_to_lonlat`, icosa, index, aperture, index_type)
}

cpp_z7_canonical_form <- function(icosa, index, max_iterations = 128L) {
    .Call(`_hexify_cpp_z7_canonical_form`, icosa, index, max_iterations)
}

cpp_build_icosa <- function(vert0_lon_deg = 11.25, vert0_lat_deg = 58.282525588538995, azimuth_deg = 0.0) {
    invisible(.Call(`_hexify_cpp_build_icosa`, vert0_lon_deg, vert0_lat_deg, azimuth_deg))
}

cpp_solid_info <- function(icosa) {
    .Call(`_hexify_cpp_solid_info`, icosa)
}

cpp_which_face <- function(icosa, lon_deg, lat_deg) {
    .Call(`_hexify_cpp_which_face`, icosa, lon_deg, lat_deg)
}

cpp_face_centers <- function(icosa) {
    .Call(`_hexify_cpp_face_centers`, icosa)
}

cpp_icosa_forward <- function(icosa, lon_deg, lat_deg) {
    .Call(`_hexify_cpp_icosa_forward`, icosa, lon_deg, lat_deg)
}

cpp_project_to_icosa_triangle <- function(icosa, face, lon_deg, lat_deg) {
    .Call(`_hexify_cpp_project_to_icosa_triangle`, icosa, face, lon_deg, lat_deg)
}

cpp_face_xy_to_ll <- function(icosa, x, y, face, newton = FALSE) {
    .Call(`_hexify_cpp_face_xy_to_ll`, icosa, x, y, face, newton)
}

cpp_snyder_triangle_forward <- function(v0, v1, v2, v) {
    .Call(`_hexify_cpp_snyder_triangle_forward`, v0, v1, v2, v)
}

cpp_snyder_triangle_inverse <- function(v0, v1, v2, b) {
    .Call(`_hexify_cpp_snyder_triangle_inverse`, v0, v1, v2, b)
}

cpp_icosa_face_params <- function(icosa, face) {
    .Call(`_hexify_cpp_icosa_face_params`, icosa, face)
}

cpp_hex_index_face_to_lonlat <- function(icosa, x, y, cen_lat, cen_lon, face_azimuth_offset, degrees = TRUE) {
    .Call(`_hexify_cpp_hex_index_face_to_lonlat`, icosa, x, y, cen_lat, cen_lon, face_azimuth_offset, degrees)
}

