# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_hex_quantify_ap3 <- function(tx, ty, resolution) {
    .Call(`_hexify_cpp_hex_quantify_ap3`, tx, ty, resolution)
}

cpp_hex_center_ap3 <- function(i, j, resolution) {
    .Call(`_hexify_cpp_hex_center_ap3`, i, j, resolution)
}

cpp_hex_corners_ap3 <- function(i, j, resolution, hex_radius = 1.0) {
    .Call(`_hexify_cpp_hex_corners_ap3`, i, j, resolution, hex_radius)
}

cpp_lonlat_to_cell_ap3 <- function(lon_deg, lat_deg, resolution) {
    .Call(`_hexify_cpp_lonlat_to_cell_ap3`, lon_deg, lat_deg, resolution)
}

cpp_cell_to_lonlat_ap3 <- function(face, i, j, resolution) {
    .Call(`_hexify_cpp_cell_to_lonlat_ap3`, face, i, j, resolution)
}

cpp_hex_quantify_ap4 <- function(tx, ty, resolution) {
    .Call(`_hexify_cpp_hex_quantify_ap4`, tx, ty, resolution)
}

cpp_hex_center_ap4 <- function(i, j, resolution) {
    .Call(`_hexify_cpp_hex_center_ap4`, i, j, resolution)
}

cpp_hex_corners_ap4 <- function(i, j, resolution, hex_radius = 1.0) {
    .Call(`_hexify_cpp_hex_corners_ap4`, i, j, resolution, hex_radius)
}

cpp_lonlat_to_cell_ap4 <- function(lon_deg, lat_deg, resolution) {
    .Call(`_hexify_cpp_lonlat_to_cell_ap4`, lon_deg, lat_deg, resolution)
}

cpp_cell_to_lonlat_ap4 <- function(face, i, j, resolution) {
    .Call(`_hexify_cpp_cell_to_lonlat_ap4`, face, i, j, resolution)
}

cpp_hex_quantify_ap7 <- function(tx, ty, resolution) {
    .Call(`_hexify_cpp_hex_quantify_ap7`, tx, ty, resolution)
}

cpp_hex_center_ap7 <- function(i, j, resolution) {
    .Call(`_hexify_cpp_hex_center_ap7`, i, j, resolution)
}

cpp_hex_corners_ap7 <- function(i, j, resolution, hex_radius = 1.0) {
    .Call(`_hexify_cpp_hex_corners_ap7`, i, j, resolution, hex_radius)
}

cpp_lonlat_to_cell_ap7 <- function(lon_deg, lat_deg, resolution) {
    .Call(`_hexify_cpp_lonlat_to_cell_ap7`, lon_deg, lat_deg, resolution)
}

cpp_cell_to_lonlat_ap7 <- function(face, i, j, resolution) {
    .Call(`_hexify_cpp_cell_to_lonlat_ap7`, face, i, j, resolution)
}

cpp_hex_quantify_ap34 <- function(tx, ty, ap_seq) {
    .Call(`_hexify_cpp_hex_quantify_ap34`, tx, ty, ap_seq)
}

cpp_hex_center_ap34 <- function(i, j, ap_seq) {
    .Call(`_hexify_cpp_hex_center_ap34`, i, j, ap_seq)
}

cpp_hex_corners_ap34 <- function(i, j, ap_seq, hex_radius = 1.0) {
    .Call(`_hexify_cpp_hex_corners_ap34`, i, j, ap_seq, hex_radius)
}

cpp_lonlat_to_cell_ap34 <- function(lon_deg, lat_deg, ap_seq) {
    .Call(`_hexify_cpp_lonlat_to_cell_ap34`, lon_deg, lat_deg, ap_seq)
}

cpp_cell_to_lonlat_ap34 <- function(face, i, j, ap_seq) {
    .Call(`_hexify_cpp_cell_to_lonlat_ap34`, face, i, j, ap_seq)
}

cpp_test_roundtrip_ap3 <- function(tx, ty, resolution) {
    .Call(`_hexify_cpp_test_roundtrip_ap3`, tx, ty, resolution)
}

cpp_test_roundtrip_ap34 <- function(tx, ty, ap_seq) {
    .Call(`_hexify_cpp_test_roundtrip_ap34`, tx, ty, ap_seq)
}

cpp_test_roundtrip_ap4 <- function(tx, ty, resolution) {
    .Call(`_hexify_cpp_test_roundtrip_ap4`, tx, ty, resolution)
}

cpp_test_roundtrip_ap7 <- function(tx, ty, resolution) {
    .Call(`_hexify_cpp_test_roundtrip_ap7`, tx, ty, resolution)
}

cpp_batch_test_roundtrip_ap3 <- function(tx_vec, ty_vec, resolution) {
    .Call(`_hexify_cpp_batch_test_roundtrip_ap3`, tx_vec, ty_vec, resolution)
}

cpp_batch_test_roundtrip_ap4 <- function(tx_vec, ty_vec, resolution) {
    .Call(`_hexify_cpp_batch_test_roundtrip_ap4`, tx_vec, ty_vec, resolution)
}

cpp_batch_test_roundtrip_ap7 <- function(tx_vec, ty_vec, resolution) {
    .Call(`_hexify_cpp_batch_test_roundtrip_ap7`, tx_vec, ty_vec, resolution)
}

cpp_cell_to_index <- function(face, i, j, resolution, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_cell_to_index`, face, i, j, resolution, aperture, index_type)
}

cpp_index_to_cell <- function(index, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_index_to_cell`, index, aperture, index_type)
}

cpp_get_parent_index <- function(index, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_get_parent_index`, index, aperture, index_type)
}

cpp_get_children_indices <- function(index, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_get_children_indices`, index, aperture, index_type)
}

cpp_get_index_resolution <- function(index, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_get_index_resolution`, index, aperture, index_type)
}

cpp_compare_indices <- function(idx1, idx2) {
    .Call(`_hexify_cpp_compare_indices`, idx1, idx2)
}

cpp_is_valid_index_type <- function(aperture, index_type) {
    .Call(`_hexify_cpp_is_valid_index_type`, aperture, index_type)
}

cpp_get_default_index_type <- function(aperture) {
    .Call(`_hexify_cpp_get_default_index_type`, aperture)
}

cpp_lonlat_to_index_ap3 <- function(lon_deg, lat_deg, resolution, index_type = "auto") {
    .Call(`_hexify_cpp_lonlat_to_index_ap3`, lon_deg, lat_deg, resolution, index_type)
}

cpp_lonlat_to_index_ap4 <- function(lon_deg, lat_deg, resolution, index_type = "auto") {
    .Call(`_hexify_cpp_lonlat_to_index_ap4`, lon_deg, lat_deg, resolution, index_type)
}

cpp_lonlat_to_index_ap7 <- function(lon_deg, lat_deg, resolution, index_type = "auto") {
    .Call(`_hexify_cpp_lonlat_to_index_ap7`, lon_deg, lat_deg, resolution, index_type)
}

cpp_lonlat_to_index <- function(lon_deg, lat_deg, resolution, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_lonlat_to_index`, lon_deg, lat_deg, resolution, aperture, index_type)
}

cpp_index_to_lonlat <- function(index, aperture, index_type = "auto") {
    .Call(`_hexify_cpp_index_to_lonlat`, index, aperture, index_type)
}

cell_to_index <- function(face, i, j, resolution, aperture, index_type = "AUTO") {
    .Call(`_hexify_cell_to_index`, face, i, j, resolution, aperture, index_type)
}

index_to_cell <- function(index, aperture, index_type = "AUTO") {
    .Call(`_hexify_index_to_cell`, index, aperture, index_type)
}

get_parent_index <- function(index, aperture, index_type = "AUTO") {
    .Call(`_hexify_get_parent_index`, index, aperture, index_type)
}

get_children_indices <- function(index, aperture, index_type = "AUTO") {
    .Call(`_hexify_get_children_indices`, index, aperture, index_type)
}

get_index_resolution <- function(index, aperture, index_type = "AUTO") {
    .Call(`_hexify_get_index_resolution`, index, aperture, index_type)
}

cpp_z7_canonical_form <- function(index, max_iterations = 128L) {
    .Call(`_hexify_cpp_z7_canonical_form`, index, max_iterations)
}

cpp_hex_index_z3_quantize_digits <- function(tx, ty, eff_res, center_thr = 0.4, flip_classes = as.logical( c())) {
    .Call(`_hexify_cpp_hex_index_z3_quantize_digits`, tx, ty, eff_res, center_thr, flip_classes)
}

cpp_hex_index_z3_center <- function(d, flip_classes = as.logical( c())) {
    .Call(`_hexify_cpp_hex_index_z3_center`, d, flip_classes)
}

cpp_hex_index_z3_corners <- function(digs, flip_classes = as.logical( c()), hex_radius = 1.0) {
    .Call(`_hexify_cpp_hex_index_z3_corners`, digs, flip_classes, hex_radius)
}

cpp_build_icosa <- function(vert0_lon_deg = 11.25, vert0_lat_deg = 58.28252559, azimuth_deg = 0.0) {
    invisible(.Call(`_hexify_cpp_build_icosa`, vert0_lon_deg, vert0_lat_deg, azimuth_deg))
}

cpp_which_face <- function(lon_deg, lat_deg) {
    .Call(`_hexify_cpp_which_face`, lon_deg, lat_deg)
}

cpp_face_centers <- function() {
    .Call(`_hexify_cpp_face_centers`)
}

cpp_snyder_forward <- function(lon_deg, lat_deg) {
    .Call(`_hexify_cpp_snyder_forward`, lon_deg, lat_deg)
}

cpp_project_to_tx_ty <- function(face, lon_deg, lat_deg) {
    .Call(`_hexify_cpp_project_to_tx_ty`, face, lon_deg, lat_deg)
}

cpp_snyder_inv_set_precision <- function(mode = "", tol = NULL, max_iters = NULL) {
    invisible(.Call(`_hexify_cpp_snyder_inv_set_precision`, mode, tol, max_iters))
}

cpp_snyder_inv_get_precision <- function() {
    .Call(`_hexify_cpp_snyder_inv_get_precision`)
}

cpp_snyder_inv_set_verbose <- function(v = TRUE) {
    invisible(.Call(`_hexify_cpp_snyder_inv_set_verbose`, v))
}

cpp_snyder_inv_get_stats_and_reset <- function() {
    .Call(`_hexify_cpp_snyder_inv_get_stats_and_reset`)
}

cpp_face_xy_to_ll <- function(x, y, face, tol = NULL, max_iters = NULL) {
    .Call(`_hexify_cpp_face_xy_to_ll`, x, y, face, tol, max_iters)
}

cpp_icosa_face_params <- function(face) {
    .Call(`_hexify_cpp_icosa_face_params`, face)
}

cpp_hex_index_face_to_lonlat <- function(x, y, cen_lat, cen_lon, dazh, degrees = TRUE, tol = NULL, max_iters = NULL) {
    .Call(`_hexify_cpp_hex_index_face_to_lonlat`, x, y, cen_lat, cen_lon, dazh, degrees, tol, max_iters)
}

cpp_lonlat_to_seqnum <- function(lon, lat, resolution, aperture) {
    .Call(`_hexify_cpp_lonlat_to_seqnum`, lon, lat, resolution, aperture)
}

cpp_seqnum_to_lonlat <- function(seqnum, resolution, aperture) {
    .Call(`_hexify_cpp_seqnum_to_lonlat`, seqnum, resolution, aperture)
}

cpp_seqnum_to_cell_info <- function(seqnum, resolution, aperture) {
    .Call(`_hexify_cpp_seqnum_to_cell_info`, seqnum, resolution, aperture)
}

cpp_decode_z7 <- function(index_body, aperture) {
    .Call(`_hexify_cpp_decode_z7`, index_body, aperture)
}

cpp_projtri_to_q2di <- function(tnum, tx, ty, aperture, resolution) {
    .Call(`_hexify_cpp_projtri_to_q2di`, tnum, tx, ty, aperture, resolution)
}

cpp_projtri_to_q2dd <- function(tnum, tx, ty) {
    .Call(`_hexify_cpp_projtri_to_q2dd`, tnum, tx, ty)
}

cpp_lonlat_to_q2di <- function(lon_deg, lat_deg, aperture, resolution) {
    .Call(`_hexify_cpp_lonlat_to_q2di`, lon_deg, lat_deg, aperture, resolution)
}

cpp_q2di_to_seqnum <- function(quad, i, j, resolution, aperture) {
    .Call(`_hexify_cpp_q2di_to_seqnum`, quad, i, j, resolution, aperture)
}

cpp_lonlat_to_seqnum_dggrid <- function(lon, lat, resolution, aperture) {
    .Call(`_hexify_cpp_lonlat_to_seqnum_dggrid`, lon, lat, resolution, aperture)
}

cpp_seqnum_to_lonlat_dggrid <- function(seqnum, resolution, aperture) {
    .Call(`_hexify_cpp_seqnum_to_lonlat_dggrid`, seqnum, resolution, aperture)
}

